In [1]:
from scripts.EvaluationsRunner import MultilabelPredictor
import pandas as pd

/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
data = pd.read_csv('simulations/data/run_1/trinucleotides_counts_sampling_1.csv')
feature_labels = data.columns[1:]
gt = pd.read_csv('simulations/ground_truth/bin_exposures.csv')
gt_labels = list(gt.columns[1:])
df = pd.merge(data, gt, on='Unnamed: 0')

df = df.iloc[:1000,:]
print(df.shape)

train_data = df.sample(frac=0.8, random_state=1)
test_data = df.drop(train_data.index)
train_data = train_data.drop(columns=['Unnamed: 0'])
test_data = test_data.drop(columns=['Unnamed: 0'])

(1000, 126)

### Multi-label Prediction

In [3]:
ml_predictor = MultilabelPredictor(
    labels=gt_labels,
    problem_types=['binary'] * len(gt_labels),
)

In [4]:
ml_predictor.fit(train_data, time_limit=10)
ml_prediction = ml_predictor.predict(test_data)

No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S1 (SBS1 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.83 GB / 15.43 GB (57.2%)
Disk Space Avail:   272.81 GB / 459.52 GB (59.4%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S1 (SBS1 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9045.17 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...

Fitting TabularPredictor for label: S1 (SBS1 - 0.99) ...

	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.89s of the 9.89s of remaining time.
	0.9563	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.85s of the 9.85s of remaining time.
	0.9563	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.83s of the 9.83s of remaining time.
	0.9625	 = Validation score   (accuracy)
	0.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.49s of the 9.49s of remaining time.
	0.9563	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 9.06s of the 9.06s of remaining time.
	0.9563	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.48s of the 8.48s of remaining time.
	0.9563	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.93s of the 7.93s of remaining time.
	0.9688	 = Validation score   (accuracy)
	3.74s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 4.19s of the 4.19s of remaining time.
	0.9563	 = Validation score   (accuracy)
	0.41s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 3.74s of the 3.74s of remaining time.
	0.9563	 = Validation score   (accuracy)
	0.41s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 3.28s of the 3.28s of remaining time.
No improvement since epoch 1: early stopping
	0.9625	 = Validation score   (accuracy)
	2.1s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.16s of the 1.16s of remaining time.
	0.9688	 = Validation score   (accuracy)
	0.35s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.8s of the 0.8s of remaining time.
	Time limit exceeded... Skipping NeuralNetTorch.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.89s of the 0.03s of remaining time.
	Ensemble Weights: {'CatBoost': 1.0}
	0.9688	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.08s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S1 (SBS1 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S2 (SBS2 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.56 GB / 15.43 GB (55.5%)
Disk Space Avail:   272.81 GB / 459.52 GB (59.4%)
===================================================
Train Data Rows:    800
Train Data Columns: 97
Label Column:       S2 (SBS2 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8761.87 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  1 | ['S1 (SBS1 - 0.99)']
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  1 | ['S1 (SBS1 - 0.99)']
	0.1s = Fit runtime
	97 features in original data used to generate 97 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.89s of the 9.88s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.87s of the 9.87s of remaining time.
	0.8313	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.85s of the 9.85s of remaining time.

Fitting TabularPredictor for label: S2 (SBS2 - 0.99) ...

	0.8688	 = Validation score   (accuracy)
	0.37s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.47s of the 9.47s of remaining time.
	0.875	 = Validation score   (accuracy)
	0.66s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.8s of the 8.8s of remaining time.
	0.85	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.22s of the 8.22s of remaining time.
	0.8438	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.65s of the 7.65s of remaining time.
	0.875	 = Validation score   (accuracy)
	2.71s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 4.94s of the 4.94s of remaining time.
	0.8125	 = Validation score   (accuracy)
	0.42s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 4.47s of the 4.47s of remaining time.
	0.825	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 4.0s of the 3.99s of remaining time.
No improvement since epoch 4: early stopping
	0.8187	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 3.44s of the 3.43s of remaining time.
	0.8688	 = Validation score   (accuracy)
	0.76s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 2.67s of the 2.67s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	0.85	 = Validation score   (accuracy)
	2.33s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 0.3s of the 0.3s of remaining time.
	Ran out of time, early stopping on iteration 45. Best iteration is:
	[23]	valid_set's binary_error: 0.175
	0.825	 = Validation score   (accuracy)
	0.32s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.89s of the -0.04s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.875	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.17s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S2 (SBS2 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S3 (SBS3 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.47 GB / 15.43 GB (54.9%)
Disk Space Avail:   272.79 GB / 459.52 GB (59.4%)
===================================================
Train Data Rows:    800
Train Data Columns: 98
Label Column:       S3 (SBS3 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8675.65 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 2 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  2 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)']
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  2 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)']
	0.1s = Fit runtime
	98 features in original data used to generate 98 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.88s of the 9.88s of remaining time.
	0.7063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.7063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.84s of the 9.84s of remaining time.

Fitting TabularPredictor for label: S3 (SBS3 - 0.97) ...

	0.7875	 = Validation score   (accuracy)
	0.63s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.18s of the 9.18s of remaining time.
	0.75	 = Validation score   (accuracy)
	0.8s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.36s of the 8.36s of remaining time.
	0.7688	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 7.79s of the 7.79s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.17s of the 7.17s of remaining time.
	0.7875	 = Validation score   (accuracy)
	3.04s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 4.13s of the 4.13s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 3.65s of the 3.65s of remaining time.
	0.7625	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 3.17s of the 3.17s of remaining time.
	0.7688	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 2.51s of the 2.51s of remaining time.
	0.7688	 = Validation score   (accuracy)
	0.9s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 1.6s of the 1.6s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	0.8313	 = Validation score   (accuracy)
	1.22s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 0.34s of the 0.34s of remaining time.
	Ran out of time, early stopping on iteration 53. Best iteration is:
	[6]	valid_set's binary_error: 0.28125
	0.7188	 = Validation score   (accuracy)
	0.36s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.88s of the -0.03s of remaining time.
	Ensemble Weights: {'LightGBMLarge': 0.5, 'NeuralNetTorch': 0.375, 'ExtraTreesEntr': 0.125}
	0.85	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.17s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S3 (SBS3 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S4 (SBS4 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.51 GB / 15.43 GB (55.1%)
Disk Space Avail:   272.76 GB / 459.52 GB (59.4%)
===================================================
Train Data Rows:    800
Train Data Columns: 99
Label Column:       S4 (SBS4 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8711.76 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  3 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)']
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  3 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)']
	0.1s = Fit runtime
	99 features in original data used to generate 99 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.88s of the 9.88s of remaining time.
	0.6438	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.6438	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.84s of the 9.84s of remaining time.

Fitting TabularPredictor for label: S4 (SBS4 - 0.98) ...

	0.7688	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.43s of the 9.43s of remaining time.
	0.7375	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.85s of the 8.84s of remaining time.
	0.7063	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.24s of the 8.23s of remaining time.
	0.6875	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.59s of the 7.59s of remaining time.
	Ran out of time, early stopping on iteration 937.
	0.7562	 = Validation score   (accuracy)
	7.6s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.88s of the -0.03s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.7688	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.12s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S4 (SBS4 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S5 (SBS5 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.47 GB / 15.43 GB (54.9%)
Disk Space Avail:   272.75 GB / 459.52 GB (59.4%)
===================================================
Train Data Rows:    800
Train Data Columns: 100
Label Column:       S5 (SBS5 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8673.42 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 4 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  4 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)']
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  4 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)']
	0.1s = Fit runtime
	100 features in original data used to generate 100 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.87s of the 9.87s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.86s of the 9.85s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.84s of the 9.84s of remaining time.

Fitting TabularPredictor for label: S5 (SBS5 - 0.98) ...

	0.825	 = Validation score   (accuracy)
	0.32s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.51s of the 9.5s of remaining time.
	0.8438	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.84s of the 8.84s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.23s of the 8.22s of remaining time.
	0.825	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.61s of the 7.61s of remaining time.
	0.825	 = Validation score   (accuracy)
	2.83s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 4.77s of the 4.77s of remaining time.
	0.8	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 4.27s of the 4.27s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.46s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 3.76s of the 3.76s of remaining time.
	0.8438	 = Validation score   (accuracy)
	0.66s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 3.09s of the 3.09s of remaining time.
	0.8375	 = Validation score   (accuracy)
	0.67s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 2.41s of the 2.41s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	0.9062	 = Validation score   (accuracy)
	2.4s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.87s of the -0.05s of remaining time.
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	0.9062	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.17s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S5 (SBS5 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S6 (SBS7a - 1.00)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.51 GB / 15.43 GB (55.2%)
Disk Space Avail:   272.74 GB / 459.52 GB (59.4%)
===================================================
Train Data Rows:    800
Train Data Columns: 101
Label Column:       S6 (SBS7a - 1.00)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8719.53 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 5 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  5 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)']
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  5 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)']
	0.1s = Fit runtime
	101 features in original data used to generate 101 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.88s of the 9.88s of remaining time.
	0.8562	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.84s of the 9.84s of remaining time.

Fitting TabularPredictor for label: S6 (SBS7a - 1.00) ...

	0.8875	 = Validation score   (accuracy)
	0.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.51s of the 9.5s of remaining time.
	0.8875	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.89s of the 8.89s of remaining time.
	0.875	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.26s of the 8.26s of remaining time.
	0.875	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.61s of the 7.61s of remaining time.
	0.8938	 = Validation score   (accuracy)
	4.41s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.2s of the 3.19s of remaining time.
	0.8688	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 2.66s of the 2.66s of remaining time.
	0.8688	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.11s of the 2.11s of remaining time.
	0.8812	 = Validation score   (accuracy)
	0.74s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.35s of the 1.35s of remaining time.
	0.8938	 = Validation score   (accuracy)
	0.88s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.46s of the 0.46s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 5)
	0.8313	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.88s of the -0.05s of remaining time.
	Ensemble Weights: {'CatBoost': 1.0}
	0.8938	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S6 (SBS7a - 1.00)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S7 (SBS7b - 0.96)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.52 GB / 15.43 GB (55.3%)
Disk Space Avail:   272.72 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 102
Label Column:       S7 (SBS7b - 0.96)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8729.79 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 6 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  6 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  6 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	102 features in original data used to generate 102 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.84s of the 9.84s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.82s of the 9.82s of remaining time.

Fitting TabularPredictor for label: S7 (SBS7b - 0.96) ...

	0.7812	 = Validation score   (accuracy)
	0.31s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.51s of the 9.51s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.87s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.62s of the 8.62s of remaining time.
	0.7375	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 7.94s of the 7.94s of remaining time.
	0.7688	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.26s of the 7.26s of remaining time.
	0.8063	 = Validation score   (accuracy)
	3.54s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.71s of the 3.71s of remaining time.
	0.725	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 3.11s of the 3.11s of remaining time.
	0.7312	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.56s of the 2.55s of remaining time.
	0.8	 = Validation score   (accuracy)
	0.71s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.82s of the 1.82s of remaining time.
	0.8125	 = Validation score   (accuracy)
	1.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.54s of the 0.54s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 6)
	0.75	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.86s of the -0.06s of remaining time.
	Ensemble Weights: {'XGBoost': 0.667, 'LightGBMXT': 0.333}
	0.8187	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.2s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S7 (SBS7b - 0.96)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S8 (SBS8 - 0.92)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.52 GB / 15.43 GB (55.2%)
Disk Space Avail:   272.70 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 103
Label Column:       S8 (SBS8 - 0.92)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8726.17 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 7 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  7 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  7 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	103 features in original data used to generate 103 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.87s of the 9.87s of remaining time.
	0.7312	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.85s of the 9.85s of remaining time.
	0.7375	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.83s of the 9.83s of remaining time.

Fitting TabularPredictor for label: S8 (SBS8 - 0.92) ...

	0.7688	 = Validation score   (accuracy)
	0.42s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.4s of the 9.4s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.75s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.64s of the 8.64s of remaining time.
	0.725	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 7.98s of the 7.98s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.31s of the 7.31s of remaining time.
	0.7688	 = Validation score   (accuracy)
	4.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 2.98s of the 2.98s of remaining time.
	0.7312	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 2.41s of the 2.41s of remaining time.
	0.75	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 1.86s of the 1.86s of remaining time.
	0.775	 = Validation score   (accuracy)
	0.75s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.09s of the 1.09s of remaining time.
	0.7688	 = Validation score   (accuracy)
	1.1s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.87s of the -0.03s of remaining time.
	Ensemble Weights: {'LightGBM': 0.7, 'NeuralNetFastAI': 0.3}
	0.8063	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S8 (SBS8 - 0.92)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S9 (SBS9 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.54 GB / 15.43 GB (55.3%)
Disk Space Avail:   272.67 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 104
Label Column:       S9 (SBS9 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8744.00 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 8 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  8 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  8 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	104 features in original data used to generate 104 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.15s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.85s of the 9.85s of remaining time.
	0.85	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.83s of the 9.83s of remaining time.

Fitting TabularPredictor for label: S9 (SBS9 - 0.94) ...

	0.8438	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.81s of the 9.81s of remaining time.
	0.8313	 = Validation score   (accuracy)
	0.32s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.48s of the 9.48s of remaining time.
	0.8438	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.99s of the 8.98s of remaining time.
	0.8	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.35s of the 8.35s of remaining time.
	0.8125	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.69s of the 7.69s of remaining time.
	0.8375	 = Validation score   (accuracy)
	3.59s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 4.09s of the 4.09s of remaining time.
	0.8125	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 3.5s of the 3.5s of remaining time.
	0.8125	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.96s of the 2.96s of remaining time.
	0.8125	 = Validation score   (accuracy)
	0.75s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 2.2s of the 2.2s of remaining time.
	0.8438	 = Validation score   (accuracy)
	0.74s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 1.44s of the 1.44s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 26)
	0.8812	 = Validation score   (accuracy)
	1.45s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.85s of the -0.07s of remaining time.
	Ensemble Weights: {'NeuralNetTorch': 0.667, 'LightGBMXT': 0.333}
	0.8875	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.22s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S9 (SBS9 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S10 (SBS10a - 1.00)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.52 GB / 15.43 GB (55.2%)
Disk Space Avail:   272.65 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 105
Label Column:       S10 (SBS10a - 1.00)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8720.61 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 9 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  9 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  9 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	105 features in original data used to generate 105 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.83s of the 9.83s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime

Fitting TabularPredictor for label: S10 (SBS10a - 1.00) ...

Fitting model: LightGBMXT ... Training model for up to 9.81s of the 9.81s of remaining time.
	0.8688	 = Validation score   (accuracy)
	0.35s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.45s of the 9.45s of remaining time.
	0.8562	 = Validation score   (accuracy)
	0.67s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.77s of the 8.77s of remaining time.
	0.85	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.14s of the 8.14s of remaining time.
	0.8313	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.48s of the 7.48s of remaining time.
	0.8625	 = Validation score   (accuracy)
	2.9s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 4.58s of the 4.57s of remaining time.
	0.85	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 3.99s of the 3.99s of remaining time.
	0.8313	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 3.44s of the 3.44s of remaining time.
No improvement since epoch 9: early stopping
	0.8375	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 2.7s of the 2.7s of remaining time.
	0.85	 = Validation score   (accuracy)
	0.82s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 1.86s of the 1.86s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 35)
	0.875	 = Validation score   (accuracy)
	1.86s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.86s of the -0.06s of remaining time.
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	0.875	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.2s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S10 (SBS10a - 1.00)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S11 (SBS10d - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.54 GB / 15.43 GB (55.3%)
Disk Space Avail:   272.63 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 106
Label Column:       S11 (SBS10d - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8740.39 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 10 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 10 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 10 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	106 features in original data used to generate 106 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.19s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()

Fitting TabularPredictor for label: S11 (SBS10d - 0.98) ...

Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.81s of the 9.81s of remaining time.
	0.7	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.79s of the 9.79s of remaining time.
	0.7125	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.77s of the 9.77s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.24s of the 9.24s of remaining time.
	0.7937	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.75s of the 8.75s of remaining time.
	0.775	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.14s of the 8.14s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.48s of the 7.48s of remaining time.
	0.8313	 = Validation score   (accuracy)
	5.46s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 2.0s of the 2.0s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 1.4s of the 1.4s of remaining time.
	0.7937	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 0.84s of the 0.84s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.81s of the 0.02s of remaining time.
	Ensemble Weights: {'CatBoost': 0.889, 'KNeighborsDist': 0.111}
	0.8375	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.1s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S11 (SBS10d - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S12 (SBS11 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.51 GB / 15.43 GB (55.2%)
Disk Space Avail:   272.61 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 107
Label Column:       S12 (SBS11 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8719.77 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 11 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 11 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 11 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	107 features in original data used to generate 107 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.7937	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.84s of the 9.84s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.82s of the 9.82s of remaining time.

Fitting TabularPredictor for label: S12 (SBS11 - 0.99) ...

	0.825	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.42s of the 9.42s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.7s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.71s of the 8.71s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.08s of the 8.08s of remaining time.
	0.8	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.43s of the 7.43s of remaining time.
	0.825	 = Validation score   (accuracy)
	4.12s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.31s of the 3.31s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 2.72s of the 2.72s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.17s of the 2.16s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.71s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.44s of the 1.44s of remaining time.
	0.8125	 = Validation score   (accuracy)
	0.85s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.58s of the 0.58s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 7)
	0.8063	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.86s of the -0.04s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.825	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.18s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S12 (SBS11 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S13 (SBS13 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.56 GB / 15.43 GB (55.5%)
Disk Space Avail:   272.59 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 108
Label Column:       S13 (SBS13 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8769.16 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 12 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 12 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 12 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	108 features in original data used to generate 108 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.7	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.84s of the 9.84s of remaining time.
	0.7063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.82s of the 9.82s of remaining time.

Fitting TabularPredictor for label: S13 (SBS13 - 0.99) ...

	0.8313	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.41s of the 9.41s of remaining time.
	0.825	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.6s of the 8.6s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 7.96s of the 7.96s of remaining time.
	0.8	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.31s of the 7.3s of remaining time.
	0.8187	 = Validation score   (accuracy)
	3.73s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.56s of the 3.56s of remaining time.
	0.7688	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 2.98s of the 2.98s of remaining time.
	0.7688	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.44s of the 2.43s of remaining time.
No improvement since epoch 8: early stopping
	0.8125	 = Validation score   (accuracy)
	0.7s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.71s of the 1.71s of remaining time.
	0.85	 = Validation score   (accuracy)
	1.04s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.66s of the 0.65s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 8)
	0.8187	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.86s of the -0.06s of remaining time.
	Ensemble Weights: {'XGBoost': 1.0}
	0.85	 = Validation score   (accuracy)
	0.11s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S13 (SBS13 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S14 (SBS14 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.53 GB / 15.43 GB (55.3%)
Disk Space Avail:   272.57 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 109
Label Column:       S14 (SBS14 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8731.58 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 13 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 13 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 13 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	109 features in original data used to generate 109 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.7063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.84s of the 9.84s of remaining time.
	0.7125	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.82s of the 9.82s of remaining time.

Fitting TabularPredictor for label: S14 (SBS14 - 0.98) ...

	0.8063	 = Validation score   (accuracy)
	0.41s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.4s of the 9.4s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.82s of the 8.82s of remaining time.
	0.7625	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.18s of the 8.18s of remaining time.
	0.7688	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.5s of the 7.5s of remaining time.
	0.7812	 = Validation score   (accuracy)
	5.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 2.16s of the 2.16s of remaining time.
	0.7312	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 1.56s of the 1.56s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 0.78s of the 0.78s of remaining time.
	Ran out of time, stopping training early. (Stopping on epoch 25)
	0.775	 = Validation score   (accuracy)
	0.82s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.86s of the -0.07s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.714, 'RandomForestEntr': 0.143, 'NeuralNetFastAI': 0.143}
	0.8187	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.22s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S14 (SBS14 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S15 (SBS15 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.38 GB / 15.43 GB (54.3%)
Disk Space Avail:   272.55 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 110
Label Column:       S15 (SBS15 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8580.69 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 14 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 14 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 14 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	110 features in original data used to generate 110 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.15s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.85s of the 9.85s of remaining time.
	0.65	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.83s of the 9.83s of remaining time.

Fitting TabularPredictor for label: S15 (SBS15 - 0.97) ...

	0.65	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.81s of the 9.81s of remaining time.
	0.75	 = Validation score   (accuracy)
	0.32s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.48s of the 9.48s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.66s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.81s of the 8.81s of remaining time.
	0.7125	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.13s of the 8.13s of remaining time.
	0.7	 = Validation score   (accuracy)
	0.64s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.43s of the 7.43s of remaining time.
	0.7438	 = Validation score   (accuracy)
	2.65s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 4.78s of the 4.78s of remaining time.
	0.725	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 4.18s of the 4.18s of remaining time.
	0.7312	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 3.59s of the 3.59s of remaining time.
No improvement since epoch 3: early stopping
	0.7438	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 2.97s of the 2.97s of remaining time.
	0.7438	 = Validation score   (accuracy)
	1.11s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 1.85s of the 1.85s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 27)
	0.7625	 = Validation score   (accuracy)
	1.83s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.85s of the -0.04s of remaining time.
	Ensemble Weights: {'NeuralNetFastAI': 0.4, 'KNeighborsDist': 0.2, 'CatBoost': 0.2, 'NeuralNetTorch': 0.2}
	0.7875	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S15 (SBS15 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S16 (SBS17 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.44 GB / 15.43 GB (54.7%)
Disk Space Avail:   272.52 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 111
Label Column:       S16 (SBS17 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8641.52 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 15 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 15 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 15 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	111 features in original data used to generate 111 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.16s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.84s of the 9.84s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.82s of the 9.81s of remaining time.

Fitting TabularPredictor for label: S16 (SBS17 - 0.99) ...

	0.7875	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.79s of the 9.79s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.36s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.43s of the 9.43s of remaining time.
	0.8438	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.74s of the 8.74s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.07s of the 8.07s of remaining time.
	0.7688	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.4s of the 7.4s of remaining time.
	0.8313	 = Validation score   (accuracy)
	3.94s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.45s of the 3.45s of remaining time.
	0.7812	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 2.91s of the 2.91s of remaining time.
	0.7562	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.2s of the 2.19s of remaining time.
No improvement since epoch 3: early stopping
	0.75	 = Validation score   (accuracy)
	0.63s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.55s of the 1.54s of remaining time.
	0.825	 = Validation score   (accuracy)
	1.43s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.1s of the 0.1s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Time limit exceeded... Skipping NeuralNetTorch.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.84s of the -0.28s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.8438	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.38s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S16 (SBS17 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S17 (SBS18 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.43 GB / 15.43 GB (54.6%)
Disk Space Avail:   272.50 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 112
Label Column:       S17 (SBS18 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8634.75 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 16 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 16 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 16 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	112 features in original data used to generate 112 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.15s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.85s of the 9.85s of remaining time.
	0.7125	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.83s of the 9.83s of remaining time.
	0.7125	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime

Fitting TabularPredictor for label: S17 (SBS18 - 0.97) ...

Fitting model: LightGBMXT ... Training model for up to 9.81s of the 9.81s of remaining time.
	0.775	 = Validation score   (accuracy)
	0.35s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.46s of the 9.46s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.86s of the 8.86s of remaining time.
	0.7812	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.3s of the 8.3s of remaining time.
	0.7625	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.73s of the 7.73s of remaining time.
	0.825	 = Validation score   (accuracy)
	3.63s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 4.1s of the 4.09s of remaining time.
	0.7312	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 3.31s of the 3.31s of remaining time.
	0.7312	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.68s of the 2.68s of remaining time.
	0.7812	 = Validation score   (accuracy)
	0.76s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.89s of the 1.89s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.99s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.89s of the 0.89s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 11)
	0.7688	 = Validation score   (accuracy)
	0.88s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.85s of the -0.05s of remaining time.
	Ensemble Weights: {'LightGBM': 0.273, 'CatBoost': 0.273, 'XGBoost': 0.273, 'LightGBMXT': 0.091, 'NeuralNetFastAI': 0.091}
	0.85	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.2s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S17 (SBS18 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S18 (SBS19 - 0.95)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.51 GB / 15.43 GB (55.2%)
Disk Space Avail:   272.48 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 113
Label Column:       S18 (SBS19 - 0.95)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8716.63 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 17 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 17 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 17 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	113 features in original data used to generate 113 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.15s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.84s of the 9.84s of remaining time.
	0.775	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.82s of the 9.82s of remaining time.

Fitting TabularPredictor for label: S18 (SBS19 - 0.95) ...

	0.775	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.8s of the 9.8s of remaining time.
	0.8313	 = Validation score   (accuracy)
	0.41s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.38s of the 9.37s of remaining time.
	0.8313	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.67s of the 8.67s of remaining time.
	0.775	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 7.99s of the 7.99s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.64s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.29s of the 7.28s of remaining time.
	0.7937	 = Validation score   (accuracy)
	5.94s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 1.34s of the 1.33s of remaining time.
	0.7812	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 0.86s of the 0.85s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 0.39s of the 0.39s of remaining time.
	Ran out of time, stopping training early. (Stopping on epoch 9)
	0.8187	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.85s of the -0.06s of remaining time.
	Ensemble Weights: {'NeuralNetFastAI': 0.5, 'LightGBMXT': 0.3, 'ExtraTreesGini': 0.1, 'ExtraTreesEntr': 0.1}
	0.8625	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.18s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S18 (SBS19 - 0.95)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S19 (SBS20 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.52 GB / 15.43 GB (55.2%)
Disk Space Avail:   272.45 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 114
Label Column:       S19 (SBS20 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8723.38 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 18 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 18 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 18 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	114 features in original data used to generate 114 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.86s of the 9.85s of remaining time.
	0.9625	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.83s of the 9.83s of remaining time.

Fitting TabularPredictor for label: S19 (SBS20 - 0.98) ...

	0.9625	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.81s of the 9.81s of remaining time.
	0.9625	 = Validation score   (accuracy)
	0.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.48s of the 9.48s of remaining time.
	0.9625	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.98s of the 8.98s of remaining time.
	0.9625	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.37s of the 8.37s of remaining time.
	0.9625	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.77s of the 7.77s of remaining time.
	0.9625	 = Validation score   (accuracy)
	2.69s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 5.07s of the 5.07s of remaining time.
	0.9625	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 4.49s of the 4.49s of remaining time.
	0.9625	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 4.0s of the 3.99s of remaining time.
	0.9688	 = Validation score   (accuracy)
	0.63s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 3.35s of the 3.35s of remaining time.
	0.9625	 = Validation score   (accuracy)
	0.34s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 3.0s of the 3.0s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	0.9625	 = Validation score   (accuracy)
	1.03s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ... Training model for up to 1.92s of the 1.92s of remaining time.
	0.9625	 = Validation score   (accuracy)
	1.18s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.86s of the 0.71s of remaining time.
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.9688	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 9.46s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S19 (SBS20 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S20 (SBS22 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.51 GB / 15.43 GB (55.1%)
Disk Space Avail:   272.45 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 115
Label Column:       S20 (SBS22 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8712.50 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 19 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 19 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 19 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	115 features in original data used to generate 115 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.6188	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.84s of the 9.84s of remaining time.
	0.6188	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.82s of the 9.82s of remaining time.

Fitting TabularPredictor for label: S20 (SBS22 - 0.99) ...

	0.7937	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.17s of the 9.17s of remaining time.
	0.8375	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.37s of the 8.37s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 7.73s of the 7.73s of remaining time.
	0.7562	 = Validation score   (accuracy)
	0.64s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.03s of the 7.03s of remaining time.
	0.7812	 = Validation score   (accuracy)
	4.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.01s of the 3.01s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 2.53s of the 2.53s of remaining time.
	0.7375	 = Validation score   (accuracy)
	0.39s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.09s of the 2.09s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.51s of the 1.51s of remaining time.
	0.8	 = Validation score   (accuracy)
	1.36s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.13s of the 0.13s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Time limit exceeded... Skipping NeuralNetTorch.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.86s of the -0.16s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.8375	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.26s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S20 (SBS22 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S21 (SBS23 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.53 GB / 15.43 GB (55.3%)
Disk Space Avail:   272.42 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 116
Label Column:       S21 (SBS23 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8733.96 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 20 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 20 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 20 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	116 features in original data used to generate 116 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.88s of the 9.87s of remaining time.
	0.7937	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.7937	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.84s of the 9.84s of remaining time.

Fitting TabularPredictor for label: S21 (SBS23 - 0.94) ...

	0.8438	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.43s of the 9.43s of remaining time.
	0.8438	 = Validation score   (accuracy)
	0.71s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.71s of the 8.71s of remaining time.
	0.8375	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.17s of the 8.17s of remaining time.
	0.8375	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.5s of the 7.49s of remaining time.
	0.8625	 = Validation score   (accuracy)
	3.99s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.5s of the 3.5s of remaining time.
	0.8063	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 2.96s of the 2.96s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.43s of the 2.43s of remaining time.
	0.8125	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.73s of the 1.73s of remaining time.
	0.8562	 = Validation score   (accuracy)
	0.74s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.98s of the 0.98s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 11)
	0.8625	 = Validation score   (accuracy)
	0.95s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.88s of the -0.05s of remaining time.
	Ensemble Weights: {'CatBoost': 0.667, 'NeuralNetTorch': 0.333}
	0.8688	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.2s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S21 (SBS23 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S22 (SBS26 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.53 GB / 15.43 GB (55.3%)
Disk Space Avail:   272.40 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 117
Label Column:       S22 (SBS26 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8732.63 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 21 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 21 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 21 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	117 features in original data used to generate 117 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.87s of the 9.87s of remaining time.
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.85s of the 9.85s of remaining time.
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.83s of the 9.83s of remaining time.

Fitting TabularPredictor for label: S22 (SBS26 - 0.94) ...

	0.8688	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.41s of the 9.41s of remaining time.
	0.8875	 = Validation score   (accuracy)
	0.8s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.59s of the 8.59s of remaining time.
	0.8562	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 7.93s of the 7.93s of remaining time.
	0.85	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.34s of the 7.34s of remaining time.
	0.8625	 = Validation score   (accuracy)
	3.71s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.62s of the 3.62s of remaining time.
	0.8438	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 3.13s of the 3.13s of remaining time.
	0.85	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.53s of the 2.52s of remaining time.
	0.8562	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.91s of the 1.91s of remaining time.
	0.875	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 1.11s of the 1.11s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 26)
	0.8688	 = Validation score   (accuracy)
	1.11s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.87s of the -0.05s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.8875	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.16s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S22 (SBS26 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S23 (SBS28 - 0.96)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.55 GB / 15.43 GB (55.4%)
Disk Space Avail:   272.38 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 118
Label Column:       S23 (SBS28 - 0.96)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8756.40 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 22 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 22 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 22 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	118 features in original data used to generate 118 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.88s of the 9.88s of remaining time.
	0.8562	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.85s of the 9.84s of remaining time.

Fitting TabularPredictor for label: S23 (SBS28 - 0.96) ...

	0.9125	 = Validation score   (accuracy)
	0.37s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.47s of the 9.47s of remaining time.
	0.9062	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.88s of the 8.88s of remaining time.
	0.8938	 = Validation score   (accuracy)
	0.46s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.37s of the 8.37s of remaining time.
	0.8875	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.84s of the 7.84s of remaining time.
	0.8938	 = Validation score   (accuracy)
	4.35s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.49s of the 3.48s of remaining time.
	0.8812	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 2.92s of the 2.92s of remaining time.
	0.8812	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.31s of the 2.31s of remaining time.
	0.8875	 = Validation score   (accuracy)
	0.82s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.47s of the 1.47s of remaining time.
	0.8938	 = Validation score   (accuracy)
	1.2s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.26s of the 0.26s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Time limit exceeded... Skipping NeuralNetTorch.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.88s of the -0.11s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.667, 'NeuralNetFastAI': 0.333}
	0.9187	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.23s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S23 (SBS28 - 0.96)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S24 (SBS31 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.57 GB / 15.43 GB (55.5%)
Disk Space Avail:   272.36 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 119
Label Column:       S24 (SBS31 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8773.03 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 23 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 23 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 23 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	119 features in original data used to generate 119 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.87s of the 9.87s of remaining time.
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.85s of the 9.85s of remaining time.
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.84s of the 9.84s of remaining time.

Fitting TabularPredictor for label: S24 (SBS31 - 0.98) ...

	0.875	 = Validation score   (accuracy)
	0.32s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.51s of the 9.51s of remaining time.
	0.8812	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.96s of the 8.96s of remaining time.
	0.8562	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.43s of the 8.43s of remaining time.
	0.8688	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.9s of the 7.9s of remaining time.
	0.8812	 = Validation score   (accuracy)
	4.59s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.3s of the 3.3s of remaining time.
	0.8562	 = Validation score   (accuracy)
	0.42s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 2.84s of the 2.83s of remaining time.
	0.8562	 = Validation score   (accuracy)
	0.37s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.41s of the 2.41s of remaining time.
	0.8688	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 1.83s of the 1.83s of remaining time.
	0.8812	 = Validation score   (accuracy)
	0.78s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 1.04s of the 1.04s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 26)
	0.875	 = Validation score   (accuracy)
	1.05s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.87s of the -0.05s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.8812	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.15s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S24 (SBS31 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S25 (SBS32 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.54 GB / 15.43 GB (55.4%)
Disk Space Avail:   272.35 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 120
Label Column:       S25 (SBS32 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8759.03 MB
	Train Data (Original)  Memory Usage: 0.60 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 24 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 24 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 24 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	120 features in original data used to generate 120 features in processed data.
	Train Data (Processed) Memory Usage: 0.60 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.89s of the 9.88s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.75	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.84s of the 9.84s of remaining time.

Fitting TabularPredictor for label: S25 (SBS32 - 0.94) ...

	0.8063	 = Validation score   (accuracy)
	0.42s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.41s of the 9.41s of remaining time.
	0.8313	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.72s of the 8.72s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.16s of the 8.16s of remaining time.
	0.8	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.59s of the 7.58s of remaining time.
	0.8313	 = Validation score   (accuracy)
	5.12s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 2.46s of the 2.46s of remaining time.
	0.7562	 = Validation score   (accuracy)
	0.44s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 1.97s of the 1.97s of remaining time.
	0.775	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 1.53s of the 1.53s of remaining time.
	0.775	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 0.94s of the 0.94s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 0.21s of the 0.21s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Time limit exceeded... Skipping NeuralNetTorch.
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.89s of the -0.09s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.8313	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S25 (SBS32 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S26 (SBS44 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.53 GB / 15.43 GB (55.3%)
Disk Space Avail:   272.33 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 121
Label Column:       S26 (SBS44 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8735.11 MB
	Train Data (Original)  Memory Usage: 0.61 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 25 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 25 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 25 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	121 features in original data used to generate 121 features in processed data.
	Train Data (Processed) Memory Usage: 0.61 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.88s of the 9.88s of remaining time.
	0.6375	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.6312	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.85s of the 9.84s of remaining time.

Fitting TabularPredictor for label: S26 (SBS44 - 0.97) ...

	0.7562	 = Validation score   (accuracy)
	0.3s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.54s of the 9.53s of remaining time.
	0.7375	 = Validation score   (accuracy)
	0.7s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.82s of the 8.82s of remaining time.
	0.7312	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.28s of the 8.28s of remaining time.
	0.7188	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.71s of the 7.71s of remaining time.
	0.7375	 = Validation score   (accuracy)
	3.88s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 3.82s of the 3.82s of remaining time.
	0.725	 = Validation score   (accuracy)
	0.44s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 3.33s of the 3.33s of remaining time.
	0.7125	 = Validation score   (accuracy)
	0.41s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 2.87s of the 2.87s of remaining time.
	0.775	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 2.28s of the 2.28s of remaining time.
	0.7375	 = Validation score   (accuracy)
	0.89s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ... Training model for up to 1.38s of the 1.38s of remaining time.
/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/sklearn/compose/_column_transformer.py:1623: FutureWarning:
The format of the columns of the 'remainder' transformer in ColumnTransformer.transformers_ will change in version 1.7 to match the format of the other transformers.
At the moment the remainder columns are stored as indices (of type int). With the same ColumnTransformer configuration, in the future they will be stored as column names (of type str).
To use the new behavior now and suppress this warning, use ColumnTransformer(force_int_remainder_cols=False).

  warnings.warn(
	Ran out of time, stopping training early. (Stopping on epoch 34)
	0.7812	 = Validation score   (accuracy)
	1.4s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.88s of the -0.14s of remaining time.
	Ensemble Weights: {'NeuralNetTorch': 0.4, 'LightGBM': 0.2, 'CatBoost': 0.2, 'ExtraTreesGini': 0.2}
	0.8063	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.26s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S26 (SBS44 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S27 (SBS88 - 0.92)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.53 GB / 15.43 GB (55.3%)
Disk Space Avail:   272.30 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 122
Label Column:       S27 (SBS88 - 0.92)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8732.97 MB
	Train Data (Original)  Memory Usage: 0.61 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 26 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 26 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 26 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	122 features in original data used to generate 122 features in processed data.
	Train Data (Processed) Memory Usage: 0.61 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.86s of the 9.86s of remaining time.
	0.75	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.85s of the 9.85s of remaining time.
	0.75	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.83s of the 9.83s of remaining time.

Fitting TabularPredictor for label: S27 (SBS88 - 0.92) ...

	0.7875	 = Validation score   (accuracy)
	0.32s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.5s of the 9.5s of remaining time.
	0.825	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.95s of the 8.95s of remaining time.
	0.7812	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 8.39s of the 8.39s of remaining time.
	0.7562	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.77s of the 7.77s of remaining time.
	0.7875	 = Validation score   (accuracy)
	6.16s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 1.6s of the 1.6s of remaining time.
	0.775	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 0.85s of the 0.85s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 0.25s of the 0.24s of remaining time.
	Ran out of time, stopping training early. (Stopping on epoch 7)
	0.7875	 = Validation score   (accuracy)
	0.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.86s of the -0.05s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.825	 = Validation score   (accuracy)
	0.09s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.16s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S27 (SBS88 - 0.92)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S28 (SBS92 - 0.95)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.47 GB / 15.43 GB (54.9%)
Disk Space Avail:   272.28 GB / 459.52 GB (59.3%)
===================================================
Train Data Rows:    800
Train Data Columns: 123
Label Column:       S28 (SBS92 - 0.95)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8673.84 MB
	Train Data (Original)  Memory Usage: 0.61 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 27 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 27 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 27 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.1s = Fit runtime
	123 features in original data used to generate 123 features in processed data.
	Train Data (Processed) Memory Usage: 0.61 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.15s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.85s of the 9.85s of remaining time.
	0.7375	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.83s of the 9.83s of remaining time.

Fitting TabularPredictor for label: S28 (SBS92 - 0.95) ...

	0.7312	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.81s of the 9.81s of remaining time.
	0.7688	 = Validation score   (accuracy)
	0.42s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.38s of the 9.38s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.82s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.55s of the 8.55s of remaining time.
	0.725	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 7.88s of the 7.87s of remaining time.
	0.7375	 = Validation score   (accuracy)
	0.69s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.11s of the 7.11s of remaining time.
	0.7937	 = Validation score   (accuracy)
	4.95s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 2.15s of the 2.15s of remaining time.
	0.75	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ... Training model for up to 1.63s of the 1.63s of remaining time.
	0.75	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ... Training model for up to 1.1s of the 1.1s of remaining time.
	0.8	 = Validation score   (accuracy)
	0.8s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ... Training model for up to 0.28s of the 0.28s of remaining time.
	0.7875	 = Validation score   (accuracy)
	0.3s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.85s of the -0.04s of remaining time.
	Ensemble Weights: {'NeuralNetFastAI': 0.933, 'KNeighborsDist': 0.067}
	0.8063	 = Validation score   (accuracy)
	0.12s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S28 (SBS92 - 0.95)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 10s
AutoGluon will save models to "AutogluonModels/ag-20250410_210311/Predictor_S29 (SBS97 - 0.95)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.41 GB / 15.43 GB (54.5%)
Disk Space Avail:   272.26 GB / 459.52 GB (59.2%)
===================================================
Train Data Rows:    800
Train Data Columns: 124
Label Column:       S29 (SBS97 - 0.95)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8612.63 MB
	Train Data (Original)  Memory Usage: 0.61 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 28 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 28 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 28 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	124 features in original data used to generate 124 features in processed data.
	Train Data (Processed) Memory Usage: 0.61 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.18s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 9.82s of the 9.82s of remaining time.

Fitting TabularPredictor for label: S29 (SBS97 - 0.95) ...

	0.675	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 9.8s of the 9.8s of remaining time.
	0.675	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 9.77s of the 9.77s of remaining time.
	0.8	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 9.34s of the 9.33s of remaining time.
	0.8187	 = Validation score   (accuracy)
	0.75s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 8.57s of the 8.57s of remaining time.
	0.725	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ... Training model for up to 7.96s of the 7.96s of remaining time.
	0.725	 = Validation score   (accuracy)
	0.64s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ... Training model for up to 7.26s of the 7.26s of remaining time.
	0.7875	 = Validation score   (accuracy)
	7.08s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ... Training model for up to 0.17s of the 0.17s of remaining time.
	0.7438	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 9.82s of the -0.49s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.8187	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 10.58s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250410_210311/Predictor_S29 (SBS97 - 0.95)")

MultilabelPredictor saved to disk. Load with: MultilabelPredictor.load('AutogluonModels/ag-20250410_210311')
Predicting with TabularPredictor for label: S1 (SBS1 - 0.99) ...
Predicting with TabularPredictor for label: S2 (SBS2 - 0.99) ...
Predicting with TabularPredictor for label: S3 (SBS3 - 0.97) ...
Predicting with TabularPredictor for label: S4 (SBS4 - 0.98) ...
Predicting with TabularPredictor for label: S5 (SBS5 - 0.98) ...
Predicting with TabularPredictor for label: S6 (SBS7a - 1.00) ...
Predicting with TabularPredictor for label: S7 (SBS7b - 0.96) ...
Predicting with TabularPredictor for label: S8 (SBS8 - 0.92) ...
Predicting with TabularPredictor for label: S9 (SBS9 - 0.94) ...
Predicting with TabularPredictor for label: S10 (SBS10a - 1.00) ...
Predicting with TabularPredictor for label: S11 (SBS10d - 0.98) ...
Predicting with TabularPredictor for label: S12 (SBS11 - 0.99) ...
Predicting with TabularPredictor for label: S13 (SBS13 - 0.99) ...
Predicting with TabularPredictor for label: S14 (SBS14 - 0.98) ...
Predicting with TabularPredictor for label: S15 (SBS15 - 0.97) ...
Predicting with TabularPredictor for label: S16 (SBS17 - 0.99) ...
Predicting with TabularPredictor for label: S17 (SBS18 - 0.97) ...
Predicting with TabularPredictor for label: S18 (SBS19 - 0.95) ...
Predicting with TabularPredictor for label: S19 (SBS20 - 0.98) ...
Predicting with TabularPredictor for label: S20 (SBS22 - 0.99) ...
Predicting with TabularPredictor for label: S21 (SBS23 - 0.94) ...
Predicting with TabularPredictor for label: S22 (SBS26 - 0.94) ...
Predicting with TabularPredictor for label: S23 (SBS28 - 0.96) ...
Predicting with TabularPredictor for label: S24 (SBS31 - 0.98) ...
Predicting with TabularPredictor for label: S25 (SBS32 - 0.94) ...
Predicting with TabularPredictor for label: S26 (SBS44 - 0.97) ...
Predicting with TabularPredictor for label: S27 (SBS88 - 0.92) ...
Predicting with TabularPredictor for label: S28 (SBS92 - 0.95) ...
Predicting with TabularPredictor for label: S29 (SBS97 - 0.95) ...

In [5]:
evalutations = ml_predictor.evaluate(test_data)

Evaluating TabularPredictor for label: S1 (SBS1 - 0.99) ...
Evaluating TabularPredictor for label: S2 (SBS2 - 0.99) ...
Evaluating TabularPredictor for label: S3 (SBS3 - 0.97) ...
Evaluating TabularPredictor for label: S4 (SBS4 - 0.98) ...
Evaluating TabularPredictor for label: S5 (SBS5 - 0.98) ...
Evaluating TabularPredictor for label: S6 (SBS7a - 1.00) ...
Evaluating TabularPredictor for label: S7 (SBS7b - 0.96) ...
Evaluating TabularPredictor for label: S8 (SBS8 - 0.92) ...
Evaluating TabularPredictor for label: S9 (SBS9 - 0.94) ...
Evaluating TabularPredictor for label: S10 (SBS10a - 1.00) ...
Evaluating TabularPredictor for label: S11 (SBS10d - 0.98) ...
Evaluating TabularPredictor for label: S12 (SBS11 - 0.99) ...
Evaluating TabularPredictor for label: S13 (SBS13 - 0.99) ...
Evaluating TabularPredictor for label: S14 (SBS14 - 0.98) ...
Evaluating TabularPredictor for label: S15 (SBS15 - 0.97) ...
Evaluating TabularPredictor for label: S16 (SBS17 - 0.99) ...
Evaluating TabularPredictor for label: S17 (SBS18 - 0.97) ...
Evaluating TabularPredictor for label: S18 (SBS19 - 0.95) ...
Evaluating TabularPredictor for label: S19 (SBS20 - 0.98) ...
Evaluating TabularPredictor for label: S20 (SBS22 - 0.99) ...
Evaluating TabularPredictor for label: S21 (SBS23 - 0.94) ...
Evaluating TabularPredictor for label: S22 (SBS26 - 0.94) ...
Evaluating TabularPredictor for label: S23 (SBS28 - 0.96) ...
Evaluating TabularPredictor for label: S24 (SBS31 - 0.98) ...
Evaluating TabularPredictor for label: S25 (SBS32 - 0.94) ...
Evaluating TabularPredictor for label: S26 (SBS44 - 0.97) ...
Evaluating TabularPredictor for label: S27 (SBS88 - 0.92) ...
Evaluating TabularPredictor for label: S28 (SBS92 - 0.95) ...
Evaluating TabularPredictor for label: S29 (SBS97 - 0.95) ...

## New Save Method

### What I want to save:
Keep in mind that I have just one sample(100%), in fact this will be made for every sampling value, so if I want to plot graphs that have various sampling level i have to wait. For the moment just **per signature graph!!!!** 
- Accuracy
- Balanced_accuracy
- Mcc
- Toc_auc
- F1
- The first 5 best model (things get complicated)
    - if the best model is an ensamble i want tho know what it is composed by, so probabily another list of model, and I want to know how much each of this model weight in the ensamble
- Quanto ogni feature risulta importante nella predizione finale

In [6]:
evalutations

{'S1 (SBS1 - 0.99)': {'accuracy': 0.94,
  'balanced_accuracy': 0.7784239604536203,
  'mcc': 0.6198993724027771,
  'roc_auc': 0.9764466414655423,
  'f1': 0.9672131147540983,
  'precision': 0.9567567567567568,
  'recall': 0.9779005524861878},
 'S2 (SBS2 - 0.99)': {'accuracy': 0.845,
  'balanced_accuracy': 0.724025974025974,
  'mcc': 0.5210068663874254,
  'roc_auc': 0.8883399209486167,
  'f1': 0.9040247678018576,
  'precision': 0.863905325443787,
  'recall': 0.948051948051948},
 'S3 (SBS3 - 0.97)': {'accuracy': 0.84,
  'balanced_accuracy': 0.8385718645102227,
  'mcc': 0.675496675857067,
  'roc_auc': 0.9426304546841624,
  'f1': 0.8181818181818182,
  'precision': 0.8089887640449438,
  'recall': 0.8275862068965517},
 'S4 (SBS4 - 0.98)': {'accuracy': 0.795,
  'balanced_accuracy': 0.7868357487922706,
  'mcc': 0.5905863785521988,
  'roc_auc': 0.911231884057971,
  'f1': 0.8240343347639485,
  'precision': 0.768,
  'recall': 0.8888888888888888},
 'S5 (SBS5 - 0.98)': {'accuracy': 0.85,
  'balanced_accuracy': 0.8114973262032086,
  'mcc': 0.6572800963301954,
  'roc_auc': 0.9273618538324421,
  'f1': 0.8913043478260869,
  'precision': 0.8541666666666666,
  'recall': 0.9318181818181818},
 'S6 (SBS7a - 1.00)': {'accuracy': 0.845,
  'balanced_accuracy': 0.614280652019844,
  'mcc': 0.3259603038956537,
  'roc_auc': 0.7946491849751948,
  'f1': 0.9116809116809117,
  'precision': 0.8648648648648649,
  'recall': 0.963855421686747},
 'S7 (SBS7b - 0.96)': {'accuracy': 0.73,
  'balanced_accuracy': 0.65,
  'mcc': 0.321898153229607,
  'roc_auc': 0.7323809523809524,
  'f1': 0.5,
  'precision': 0.5625,
  'recall': 0.45},
 'S8 (SBS8 - 0.92)': {'accuracy': 0.745,
  'balanced_accuracy': 0.7414322250639387,
  'mcc': 0.480876183519391,
  'roc_auc': 0.8431713554987212,
  'f1': 0.775330396475771,
  'precision': 0.7857142857142857,
  'recall': 0.7652173913043478},
 'S9 (SBS9 - 0.94)': {'accuracy': 0.85,
  'balanced_accuracy': 0.7961997451048546,
  'mcc': 0.6398213395887058,
  'roc_auc': 0.8996640018537828,
  'f1': 0.7321428571428571,
  'precision': 0.8367346938775511,
  'recall': 0.6507936507936508},
 'S10 (SBS10a - 1.00)': {'accuracy': 0.805,
  'balanced_accuracy': 0.71,
  'mcc': 0.45049443614715134,
  'roc_auc': 0.8258666666666666,
  'f1': 0.5714285714285714,
  'precision': 0.6341463414634146,
  'recall': 0.52},
 'S11 (SBS10d - 0.98)': {'accuracy': 0.675,
  'balanced_accuracy': 0.611003861003861,
  'mcc': 0.25668300033378955,
  'roc_auc': 0.7080652080652081,
  'f1': 0.453781512605042,
  'precision': 0.6,
  'recall': 0.36486486486486486},
 'S12 (SBS11 - 0.99)': {'accuracy': 0.815,
  'balanced_accuracy': 0.5511517615176151,
  'mcc': 0.172399705475229,
  'roc_auc': 0.6473577235772359,
  'f1': 0.2127659574468085,
  'precision': 0.45454545454545453,
  'recall': 0.1388888888888889},
 'S13 (SBS13 - 0.99)': {'accuracy': 0.815,
  'balanced_accuracy': 0.8069053708439897,
  'mcc': 0.6193801042615005,
  'roc_auc': 0.8860358056265984,
  'f1': 0.8425531914893617,
  'precision': 0.825,
  'recall': 0.8608695652173913},
 'S14 (SBS14 - 0.98)': {'accuracy': 0.7,
  'balanced_accuracy': 0.5202942668696093,
  'mcc': 0.06006554474662097,
  'roc_auc': 0.6624809741248098,
  'f1': 0.1891891891891892,
  'precision': 0.35,
  'recall': 0.12962962962962962},
 'S15 (SBS15 - 0.97)': {'accuracy': 0.7,
  'balanced_accuracy': 0.7019704433497538,
  'mcc': 0.39905629488495203,
  'roc_auc': 0.7922824302134648,
  'f1': 0.6666666666666666,
  'precision': 0.625,
  'recall': 0.7142857142857143},
 'S16 (SBS17 - 0.99)': {'accuracy': 0.845,
  'balanced_accuracy': 0.8325095252806096,
  'mcc': 0.6786798125150952,
  'roc_auc': 0.9293584594789415,
  'f1': 0.802547770700637,
  'precision': 0.8513513513513513,
  'recall': 0.7590361445783133},
 'S17 (SBS18 - 0.97)': {'accuracy': 0.82,
  'balanced_accuracy': 0.8222492155076424,
  'mcc': 0.6408758075072074,
  'roc_auc': 0.8956372102439518,
  'f1': 0.8064516129032258,
  'precision': 0.7731958762886598,
  'recall': 0.8426966292134831},
 'S18 (SBS19 - 0.95)': {'accuracy': 0.74,
  'balanced_accuracy': 0.7309818108732791,
  'mcc': 0.4815230832015833,
  'roc_auc': 0.7986132047030449,
  'f1': 0.6829268292682927,
  'precision': 0.7887323943661971,
  'recall': 0.6021505376344086},
 'S19 (SBS20 - 0.98)': {'accuracy': 0.955,
  'balanced_accuracy': 0.49739583333333337,
  'mcc': -0.014469977004330817,
  'roc_auc': 0.662109375,
  'f1': 0.0,
  'precision': 0.0,
  'recall': 0.0},
 'S20 (SBS22 - 0.99)': {'accuracy': 0.62,
  'balanced_accuracy': 0.603448275862069,
  'mcc': 0.2103799034233465,
  'roc_auc': 0.681547619047619,
  'f1': 0.525,
  'precision': 0.5526315789473685,
  'recall': 0.5},
 'S21 (SBS23 - 0.94)': {'accuracy': 0.81,
  'balanced_accuracy': 0.583469115686565,
  'mcc': 0.30082409399099236,
  'roc_auc': 0.7601836764923715,
  'f1': 0.2962962962962963,
  'precision': 0.7272727272727273,
  'recall': 0.18604651162790697},
 'S22 (SBS26 - 0.94)': {'accuracy': 0.815,
  'balanced_accuracy': 0.77278610721605,
  'mcc': 0.5916191548009946,
  'roc_auc': 0.8863121561859563,
  'f1': 0.7086614173228346,
  'precision': 0.8333333333333334,
  'recall': 0.6164383561643836},
 'S23 (SBS28 - 0.96)': {'accuracy': 0.79,
  'balanced_accuracy': 0.6273291925465838,
  'mcc': 0.3186661686395081,
  'roc_auc': 0.76171654432524,
  'f1': 0.4166666666666667,
  'precision': 0.5769230769230769,
  'recall': 0.32608695652173914},
 'S24 (SBS31 - 0.98)': {'accuracy': 0.84,
  'balanced_accuracy': 0.5411055988660525,
  'mcc': 0.22058015962692945,
  'roc_auc': 0.799078667611623,
  'f1': 0.15789473684210525,
  'precision': 0.75,
  'recall': 0.08823529411764706},
 'S25 (SBS32 - 0.94)': {'accuracy': 0.755,
  'balanced_accuracy': 0.6929416970903861,
  'mcc': 0.42951058421748217,
  'roc_auc': 0.8300696979754398,
  'f1': 0.5811965811965812,
  'precision': 0.7083333333333334,
  'recall': 0.4927536231884058},
 'S26 (SBS44 - 0.97)': {'accuracy': 0.705,
  'balanced_accuracy': 0.6183853459972863,
  'mcc': 0.27577939839984733,
  'roc_auc': 0.7009271822704658,
  'f1': 0.4485981308411215,
  'precision': 0.5853658536585366,
  'recall': 0.36363636363636365},
 'S27 (SBS88 - 0.92)': {'accuracy': 0.79,
  'balanced_accuracy': 0.7253918495297805,
  'mcc': 0.4618014865622106,
  'roc_auc': 0.8171786833855801,
  'f1': 0.8571428571428571,
  'precision': 0.8456375838926175,
  'recall': 0.8689655172413793},
 'S28 (SBS92 - 0.95)': {'accuracy': 0.745,
  'balanced_accuracy': 0.7050252291216147,
  'mcc': 0.48009811672543135,
  'roc_auc': 0.8673669035114818,
  'f1': 0.8118081180811808,
  'precision': 0.7142857142857143,
  'recall': 0.9401709401709402},
 'S29 (SBS97 - 0.95)': {'accuracy': 0.72,
  'balanced_accuracy': 0.7080808080808081,
  'mcc': 0.43132872904874514,
  'roc_auc': 0.7915151515151516,
  'f1': 0.654320987654321,
  'precision': 0.7361111111111112,
  'recall': 0.5888888888888889}}

In [7]:
pred = signature_list = list(evalutations)
p = ml_predictor.get_predictor(signature_list[0])
p.leaderboard()

,model,score_val,eval_metric,pred_time_val,fit_time,pred_time_val_marginal,fit_time_marginal,stack_level,can_infer,fit_order
0,CatBoost,0.96875,accuracy,0.002267,3.738123,0.002267,3.738123,1,True,7
1,XGBoost,0.96875,accuracy,0.002695,0.350939,0.002695,0.350939,1,True,11
2,WeightedEnsemble_L2,0.96875,accuracy,0.002891,3.829360,0.000623,0.091236,2,True,12
3,LightGBMXT,0.96250,accuracy,0.002643,0.333283,0.002643,0.333283,1,True,3
4,NeuralNetFastAI,0.96250,accuracy,0.006308,2.101573,0.006308,2.101573,1,True,10
5,LightGBM,0.95625,accuracy,0.001870,0.428049,0.001870,0.428049,1,True,4
6,KNeighborsDist,0.95625,accuracy,0.002406,0.011039,0.002406,0.011039,1,True,2
7,KNeighborsUnif,0.95625,accuracy,0.018183,0.016588,0.018183,0.016588,1,True,1
8,RandomForestGini,0.95625,accuracy,0.033896,0.534950,0.033896,0.534950,1,True,5
9,ExtraTreesEntr,0.95625,accuracy,0.033912,0.411045,0.033912,0.411045,1,True,9
10,RandomForestEntr,0.95625,accuracy,0.034866,0.501628,0.034866,0.501628,1,True,6
11,ExtraTreesGini,0.95625,accuracy,0.034929,0.407435,0.034929,0.407435,1,True,8

In [ ]:
import json

def save_results(predictor, test_data, output_path='results_summary.json'):
    evaluations = predictor.evaluate(test_data)
    results = []

    for signature in evaluations:
        model_predictor = predictor.get_predictor(signature)
        metrics = evaluations[signature]
        info = model_predictor.info()
        model_info = info['model_info']

        best_model_name = info['best_model']
        best_model_info = model_info[best_model_name]

        ensemble_model_names = best_model_info.get('features', [])

        ensemble_info = [
            {
                'model_name': model,
                'val_score': model_info[model].get('val_score'),
                'fit_time': model_info[model].get('fit_time')
            }
            for model in ensemble_model_names
        ]

        result = {
            'signature': signature,
            'best_model': best_model_name,
            'best_model_val_score': best_model_info.get('val_score'),
            'best_model_metrics': metrics,
            'best_model_fit_time': best_model_info.get('fit_time'),
            'ensemble_models': ensemble_model_names,
            'ensemble_info': ensemble_info
        }

        results.append(result)

    # Salvataggio su file JSON
    with open(output_path, 'w') as f:
        json.dump(results, f, indent=4)  # indent=4 per renderlo leggibile

    print(f"✅ Risultati salvati in '{output_path}'")

    return results

In [10]:
results_summary = save_results(ml_predictor, test_data, output_path='results_summary.json')

Evaluating TabularPredictor for label: S1 (SBS1 - 0.99) ...
Evaluating TabularPredictor for label: S2 (SBS2 - 0.99) ...
Evaluating TabularPredictor for label: S3 (SBS3 - 0.97) ...
Evaluating TabularPredictor for label: S4 (SBS4 - 0.98) ...
Evaluating TabularPredictor for label: S5 (SBS5 - 0.98) ...
Evaluating TabularPredictor for label: S6 (SBS7a - 1.00) ...
Evaluating TabularPredictor for label: S7 (SBS7b - 0.96) ...
Evaluating TabularPredictor for label: S8 (SBS8 - 0.92) ...
Evaluating TabularPredictor for label: S9 (SBS9 - 0.94) ...
Evaluating TabularPredictor for label: S10 (SBS10a - 1.00) ...
Evaluating TabularPredictor for label: S11 (SBS10d - 0.98) ...
Evaluating TabularPredictor for label: S12 (SBS11 - 0.99) ...
Evaluating TabularPredictor for label: S13 (SBS13 - 0.99) ...
Evaluating TabularPredictor for label: S14 (SBS14 - 0.98) ...
Evaluating TabularPredictor for label: S15 (SBS15 - 0.97) ...
Evaluating TabularPredictor for label: S16 (SBS17 - 0.99) ...
Evaluating TabularPredictor for label: S17 (SBS18 - 0.97) ...
Evaluating TabularPredictor for label: S18 (SBS19 - 0.95) ...
Evaluating TabularPredictor for label: S19 (SBS20 - 0.98) ...
Evaluating TabularPredictor for label: S20 (SBS22 - 0.99) ...
Evaluating TabularPredictor for label: S21 (SBS23 - 0.94) ...
Evaluating TabularPredictor for label: S22 (SBS26 - 0.94) ...
Evaluating TabularPredictor for label: S23 (SBS28 - 0.96) ...
Evaluating TabularPredictor for label: S24 (SBS31 - 0.98) ...
Evaluating TabularPredictor for label: S25 (SBS32 - 0.94) ...
Evaluating TabularPredictor for label: S26 (SBS44 - 0.97) ...
Evaluating TabularPredictor for label: S27 (SBS88 - 0.92) ...
Evaluating TabularPredictor for label: S28 (SBS92 - 0.95) ...
Evaluating TabularPredictor for label: S29 (SBS97 - 0.95) ...
✅ Risultati salvati in 'results_summary.json'

### Non multilabel Prediction

In [ ]:
predictor = MultilabelPredictor(
    labels=gt_labels,
    problem_types=['binary'] * len(gt_labels),
    consider_labels_correlation=False,
    )

No path specified. Models will be saved in: "AutogluonModels/ag-20250407_205054"

In [ ]:
predictor.fit(train_data, time_limit=None)
prediction = predictor.predict(test_data)

No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S1 (SBS1 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.27 GB / 15.43 GB (53.6%)
Disk Space Avail:   280.52 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S1 (SBS1 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8468.81 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.9563	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.9563	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S1 (SBS1 - 0.99) ...

	0.9625	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.9563	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.9563	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.9563	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	0.9688	 = Validation score   (accuracy)
	3.97s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.9563	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.9563	 = Validation score   (accuracy)
	0.44s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 1: early stopping
	0.9625	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.9688	 = Validation score   (accuracy)
	0.38s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.9625	 = Validation score   (accuracy)
	1.76s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.975	 = Validation score   (accuracy)
	0.93s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBMLarge': 1.0}
	0.975	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 11.17s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S1 (SBS1 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S2 (SBS2 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.31 GB / 15.43 GB (53.9%)
Disk Space Avail:   280.51 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S2 (SBS2 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8514.16 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.8187	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.8313	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S2 (SBS2 - 0.99) ...

	0.8562	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8812	 = Validation score   (accuracy)
	0.78s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8438	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8375	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	0.8688	 = Validation score   (accuracy)
	3.27s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8375	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8313	 = Validation score   (accuracy)
	0.46s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 5: early stopping
	0.8063	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.8688	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.85	 = Validation score   (accuracy)
	2.13s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8688	 = Validation score   (accuracy)
	2.01s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBM': 1.0}
	0.8812	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 12.83s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S2 (SBS2 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S3 (SBS3 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.32 GB / 15.43 GB (53.9%)
Disk Space Avail:   280.49 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S3 (SBS3 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8517.66 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S3 (SBS3 - 0.97) ...

	0.8	 = Validation score   (accuracy)
	0.46s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.75	 = Validation score   (accuracy)
	0.9s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7625	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7812	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	0.7688	 = Validation score   (accuracy)
	3.5s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7438	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.75	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7812	 = Validation score   (accuracy)
	0.69s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7562	 = Validation score   (accuracy)
	0.78s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.85	 = Validation score   (accuracy)
	2.57s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.7625	 = Validation score   (accuracy)
	2.07s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	0.85	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 13.77s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S3 (SBS3 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S4 (SBS4 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.31 GB / 15.43 GB (53.9%)
Disk Space Avail:   280.46 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S4 (SBS4 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8512.30 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.6438	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.6438	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S4 (SBS4 - 0.98) ...

	0.7312	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.7312	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	0.7438	 = Validation score   (accuracy)
	3.49s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.6875	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7875	 = Validation score   (accuracy)
	0.69s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7438	 = Validation score   (accuracy)
	1.08s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.7625	 = Validation score   (accuracy)
	1.64s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.7375	 = Validation score   (accuracy)
	1.97s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetFastAI': 0.714, 'KNeighborsDist': 0.143, 'ExtraTreesGini': 0.143}
	0.8063	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 12.93s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S4 (SBS4 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S5 (SBS5 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.28 GB / 15.43 GB (53.7%)
Disk Space Avail:   280.43 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S5 (SBS5 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8483.11 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.11s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.8187	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.8187	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S5 (SBS5 - 0.98) ...

	0.8438	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8375	 = Validation score   (accuracy)
	0.87s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.825	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.825	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	0.825	 = Validation score   (accuracy)
	5.32s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8125	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8063	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.875	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.8438	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8875	 = Validation score   (accuracy)
	2.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8375	 = Validation score   (accuracy)
	1.96s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 0.667, 'ExtraTreesGini': 0.167, 'NeuralNetFastAI': 0.167}
	0.9125	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 15.64s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S5 (SBS5 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S6 (SBS7a - 1.00)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.34 GB / 15.43 GB (54.0%)
Disk Space Avail:   280.41 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S6 (SBS7a - 1.00)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8540.86 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.8562	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime

Fitting TabularPredictor for label: S6 (SBS7a - 1.00) ...

Fitting model: LightGBMXT ...
	0.8812	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	0.8812	 = Validation score   (accuracy)
	0.7s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8688	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8688	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8812	 = Validation score   (accuracy)
	3.74s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.85	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.85	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 0: early stopping
	0.8375	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.875	 = Validation score   (accuracy)
	0.76s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.875	 = Validation score   (accuracy)
	1.99s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.875	 = Validation score   (accuracy)
	1.7s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBMXT': 0.5, 'RandomForestEntr': 0.5}
	0.8875	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 12.98s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S6 (SBS7a - 1.00)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S7 (SBS7b - 0.96)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.31 GB / 15.43 GB (53.9%)
Disk Space Avail:   280.39 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S7 (SBS7b - 0.96)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8512.30 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7438	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7438	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S7 (SBS7b - 0.96) ...

	0.7937	 = Validation score   (accuracy)
	0.42s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7562	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7375	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.7875	 = Validation score   (accuracy)
	6.46s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7312	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7312	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 9: early stopping
	0.7875	 = Validation score   (accuracy)
	0.69s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7875	 = Validation score   (accuracy)
	0.89s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8375	 = Validation score   (accuracy)
	2.58s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.775	 = Validation score   (accuracy)
	1.62s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	0.8375	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 16.05s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S7 (SBS7b - 0.96)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S8 (SBS8 - 0.92)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.32 GB / 15.43 GB (53.9%)
Disk Space Avail:   280.37 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S8 (SBS8 - 0.92)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8515.63 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7312	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7375	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S8 (SBS8 - 0.92) ...

	0.8	 = Validation score   (accuracy)
	0.44s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.7937	 = Validation score   (accuracy)
	0.85s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7312	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.7625	 = Validation score   (accuracy)
	6.83s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7125	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7125	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7875	 = Validation score   (accuracy)
	0.7s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7562	 = Validation score   (accuracy)
	0.99s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8313	 = Validation score   (accuracy)
	2.46s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.7562	 = Validation score   (accuracy)
	2.05s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 0.667, 'NeuralNetFastAI': 0.333}
	0.8562	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 17.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S8 (SBS8 - 0.92)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S9 (SBS9 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.30 GB / 15.43 GB (53.8%)
Disk Space Avail:   280.34 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S9 (SBS9 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8499.24 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.85	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.8438	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S9 (SBS9 - 0.94) ...

	0.85	 = Validation score   (accuracy)
	0.42s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.85	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.85	 = Validation score   (accuracy)
	3.79s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8063	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7812	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 9: early stopping
	0.7937	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.8562	 = Validation score   (accuracy)
	0.74s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.875	 = Validation score   (accuracy)
	3.23s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8187	 = Validation score   (accuracy)
	1.73s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	0.875	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 14.16s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S9 (SBS9 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S10 (SBS10a - 1.00)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.31 GB / 15.43 GB (53.9%)
Disk Space Avail:   280.32 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S10 (SBS10a - 1.00)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8513.39 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.8063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.8063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S10 (SBS10a - 1.00) ...

	0.85	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.85	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.825	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8375	 = Validation score   (accuracy)
	0.64s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost ...
	0.85	 = Validation score   (accuracy)
	2.75s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8187	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8313	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.8562	 = Validation score   (accuracy)
	0.73s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.8562	 = Validation score   (accuracy)
	0.75s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8438	 = Validation score   (accuracy)
	1.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.85	 = Validation score   (accuracy)
	1.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBM': 0.429, 'KNeighborsDist': 0.286, 'NeuralNetFastAI': 0.286}
	0.875	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 11.96s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S10 (SBS10a - 1.00)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S11 (SBS10d - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.23 GB / 15.43 GB (53.4%)
Disk Space Avail:   280.30 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S11 (SBS10d - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8429.95 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7125	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S11 (SBS10d - 0.98) ...

	0.8	 = Validation score   (accuracy)
	0.37s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.7875	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7625	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8063	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8	 = Validation score   (accuracy)
	4.09s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.775	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7312	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7562	 = Validation score   (accuracy)
	0.73s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7812	 = Validation score   (accuracy)
	0.95s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.7875	 = Validation score   (accuracy)
	2.34s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.7875	 = Validation score   (accuracy)
	2.05s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'RandomForestEntr': 1.0}
	0.8063	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 14.13s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S11 (SBS10d - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S12 (SBS11 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.23 GB / 15.43 GB (53.3%)
Disk Space Avail:   280.27 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S12 (SBS11 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8426.73 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7937	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7875	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S12 (SBS11 - 0.99) ...

	0.8063	 = Validation score   (accuracy)
	0.39s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8125	 = Validation score   (accuracy)
	0.71s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8125	 = Validation score   (accuracy)
	4.25s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8063	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8063	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.8	 = Validation score   (accuracy)
	0.75s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.8187	 = Validation score   (accuracy)
	0.78s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8375	 = Validation score   (accuracy)
	3.5s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.825	 = Validation score   (accuracy)
	1.66s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	0.8375	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 14.94s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S12 (SBS11 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S13 (SBS13 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.23 GB / 15.43 GB (53.3%)
Disk Space Avail:   280.25 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S13 (SBS13 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8427.02 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S13 (SBS13 - 0.99) ...

	0.8562	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8375	 = Validation score   (accuracy)
	0.69s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8063	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8313	 = Validation score   (accuracy)
	4.94s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7812	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7812	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7812	 = Validation score   (accuracy)
	0.75s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.8313	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.85	 = Validation score   (accuracy)
	2.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8063	 = Validation score   (accuracy)
	1.73s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetFastAI': 0.333, 'LightGBMXT': 0.167, 'RandomForestEntr': 0.167, 'NeuralNetTorch': 0.167, 'LightGBMLarge': 0.167}
	0.8875	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 14.75s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S13 (SBS13 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S14 (SBS14 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.23 GB / 15.43 GB (53.4%)
Disk Space Avail:   280.23 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S14 (SBS14 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8431.71 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7063	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7125	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S14 (SBS14 - 0.98) ...

	0.775	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.7875	 = Validation score   (accuracy)
	0.76s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7438	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7625	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost ...
	0.7875	 = Validation score   (accuracy)
	3.93s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.75	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7625	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.75	 = Validation score   (accuracy)
	0.78s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7812	 = Validation score   (accuracy)
	0.91s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.7688	 = Validation score   (accuracy)
	3.33s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.775	 = Validation score   (accuracy)
	1.81s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBM': 0.6, 'NeuralNetTorch': 0.2, 'RandomForestGini': 0.133, 'KNeighborsUnif': 0.067}
	0.825	 = Validation score   (accuracy)
	0.19s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 15.24s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S14 (SBS14 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S15 (SBS15 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.08 GB / 15.43 GB (52.4%)
Disk Space Avail:   280.21 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S15 (SBS15 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8276.16 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.14s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.65	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...

Fitting TabularPredictor for label: S15 (SBS15 - 0.97) ...

	0.65	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...
	0.7125	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.7125	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.6875	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.6875	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.7188	 = Validation score   (accuracy)
	2.54s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.675	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7063	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 4: early stopping
	0.6438	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7063	 = Validation score   (accuracy)
	1.17s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.725	 = Validation score   (accuracy)
	1.54s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.7188	 = Validation score   (accuracy)
	2.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'CatBoost': 0.667, 'NeuralNetTorch': 0.333}
	0.75	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 11.84s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S15 (SBS15 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S16 (SBS17 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.27 GB / 15.43 GB (53.6%)
Disk Space Avail:   280.18 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S16 (SBS17 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8466.36 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7875	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7875	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S16 (SBS17 - 0.99) ...

	0.825	 = Validation score   (accuracy)
	0.35s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8187	 = Validation score   (accuracy)
	0.58s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7812	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7875	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8187	 = Validation score   (accuracy)
	2.22s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7937	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7688	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 8: early stopping
	0.75	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.825	 = Validation score   (accuracy)
	1.1s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.85	 = Validation score   (accuracy)
	2.17s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.825	 = Validation score   (accuracy)
	1.82s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 0.375, 'KNeighborsUnif': 0.25, 'ExtraTreesEntr': 0.25, 'NeuralNetFastAI': 0.125}
	0.8688	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 11.8s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S16 (SBS17 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S17 (SBS18 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.41 GB / 15.43 GB (54.5%)
Disk Space Avail:   280.16 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S17 (SBS18 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8615.45 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7125	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7125	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S17 (SBS18 - 0.97) ...

	0.8375	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	0.8063	 = Validation score   (accuracy)
	0.87s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.775	 = Validation score   (accuracy)
	0.79s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8063	 = Validation score   (accuracy)
	0.66s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8187	 = Validation score   (accuracy)
	2.84s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7937	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8063	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.8	 = Validation score   (accuracy)
	0.76s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.85	 = Validation score   (accuracy)
	1.04s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8313	 = Validation score   (accuracy)
	2.32s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.7937	 = Validation score   (accuracy)
	2.44s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'XGBoost': 0.5, 'NeuralNetFastAI': 0.333, 'RandomForestGini': 0.167}
	0.8625	 = Validation score   (accuracy)
	0.1s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 14.15s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S17 (SBS18 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S18 (SBS19 - 0.95)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.68 GB / 15.43 GB (56.2%)
Disk Space Avail:   280.14 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S18 (SBS19 - 0.95)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8887.09 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.775	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.775	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime

Fitting TabularPredictor for label: S18 (SBS19 - 0.95) ...

Fitting model: LightGBMXT ...
	0.8187	 = Validation score   (accuracy)
	0.4s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8313	 = Validation score   (accuracy)
	0.7s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.775	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7812	 = Validation score   (accuracy)
	0.6s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8063	 = Validation score   (accuracy)
	4.98s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7875	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7937	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.8187	 = Validation score   (accuracy)
	0.73s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7937	 = Validation score   (accuracy)
	0.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8375	 = Validation score   (accuracy)
	2.98s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8125	 = Validation score   (accuracy)
	1.77s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBMLarge': 0.5, 'NeuralNetTorch': 0.3, 'XGBoost': 0.2}
	0.85	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 15.48s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S18 (SBS19 - 0.95)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S19 (SBS20 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.78 GB / 15.43 GB (56.9%)
Disk Space Avail:   280.12 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S19 (SBS20 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8987.20 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.9625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.9625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S19 (SBS20 - 0.98) ...

	0.9625	 = Validation score   (accuracy)
	0.33s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.9625	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.9625	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.9625	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	0.9625	 = Validation score   (accuracy)
	2.15s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.9625	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.9625	 = Validation score   (accuracy)
	0.44s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 8: early stopping
	0.9688	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.9625	 = Validation score   (accuracy)
	0.35s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.9625	 = Validation score   (accuracy)
	1.17s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.9625	 = Validation score   (accuracy)
	1.22s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetFastAI': 1.0}
	0.9688	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 9.07s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S19 (SBS20 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S20 (SBS22 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.75 GB / 15.43 GB (56.7%)
Disk Space Avail:   280.11 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S20 (SBS22 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8957.57 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.6188	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.6188	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S20 (SBS22 - 0.99) ...

	0.7875	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8	 = Validation score   (accuracy)
	0.63s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.75	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7188	 = Validation score   (accuracy)
	0.61s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.7688	 = Validation score   (accuracy)
	5.41s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.6875	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.6813	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
No improvement since epoch 8: early stopping
	0.7562	 = Validation score   (accuracy)
	0.76s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7625	 = Validation score   (accuracy)
	1.29s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8	 = Validation score   (accuracy)
	2.05s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.7875	 = Validation score   (accuracy)
	1.88s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBM': 1.0}
	0.8	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 15.6s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S20 (SBS22 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S21 (SBS23 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.73 GB / 15.43 GB (56.6%)
Disk Space Avail:   280.08 GB / 459.52 GB (61.0%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S21 (SBS23 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8942.22 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.16s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...

Fitting TabularPredictor for label: S21 (SBS23 - 0.94) ...

	0.7937	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7937	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...
	0.875	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	0.8625	 = Validation score   (accuracy)
	0.71s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8313	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.85	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8625	 = Validation score   (accuracy)
	2.87s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8375	 = Validation score   (accuracy)
	0.5s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8438	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.8063	 = Validation score   (accuracy)
	0.66s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.875	 = Validation score   (accuracy)
	0.86s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8625	 = Validation score   (accuracy)
	1.56s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8562	 = Validation score   (accuracy)
	1.74s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'XGBoost': 0.5, 'LightGBMXT': 0.333, 'NeuralNetTorch': 0.167}
	0.8938	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 11.83s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S21 (SBS23 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S22 (SBS26 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.75 GB / 15.43 GB (56.7%)
Disk Space Avail:   280.06 GB / 459.52 GB (60.9%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S22 (SBS26 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8957.42 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S22 (SBS26 - 0.94) ...

	0.8562	 = Validation score   (accuracy)
	0.46s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8812	 = Validation score   (accuracy)
	0.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.85	 = Validation score   (accuracy)
	0.64s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.85	 = Validation score   (accuracy)
	0.64s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.875	 = Validation score   (accuracy)
	4.58s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.85	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8438	 = Validation score   (accuracy)
	0.44s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.8875	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.875	 = Validation score   (accuracy)
	0.69s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8625	 = Validation score   (accuracy)
	1.28s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.875	 = Validation score   (accuracy)
	1.87s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetFastAI': 0.75, 'CatBoost': 0.25}
	0.9	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 13.4s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S22 (SBS26 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S23 (SBS28 - 0.96)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.80 GB / 15.43 GB (57.1%)
Disk Space Avail:   280.03 GB / 459.52 GB (60.9%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S23 (SBS28 - 0.96)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9014.36 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.8562	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S23 (SBS28 - 0.96) ...

	0.8875	 = Validation score   (accuracy)
	0.35s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8938	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8812	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8812	 = Validation score   (accuracy)
	0.53s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8875	 = Validation score   (accuracy)
	3.68s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8812	 = Validation score   (accuracy)
	0.54s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8812	 = Validation score   (accuracy)
	0.78s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.8812	 = Validation score   (accuracy)
	0.86s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.8812	 = Validation score   (accuracy)
	0.8s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.9062	 = Validation score   (accuracy)
	3.81s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8688	 = Validation score   (accuracy)
	1.88s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	0.9062	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 15.21s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S23 (SBS28 - 0.96)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S24 (SBS31 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.25 GB / 15.43 GB (53.4%)
Disk Space Avail:   280.01 GB / 459.52 GB (60.9%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S24 (SBS31 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8443.91 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.8625	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.8625	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S24 (SBS31 - 0.98) ...

	0.9	 = Validation score   (accuracy)
	0.48s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8688	 = Validation score   (accuracy)
	0.64s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.8688	 = Validation score   (accuracy)
	0.59s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.8625	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.8875	 = Validation score   (accuracy)
	3.94s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.8562	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.8562	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.8625	 = Validation score   (accuracy)
	0.86s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.875	 = Validation score   (accuracy)
	0.94s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8625	 = Validation score   (accuracy)
	1.77s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8688	 = Validation score   (accuracy)
	1.6s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.9	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 13.26s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S24 (SBS31 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S25 (SBS32 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.27 GB / 15.43 GB (53.6%)
Disk Space Avail:   279.99 GB / 459.52 GB (60.9%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S25 (SBS32 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8467.20 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.7438	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.75	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S25 (SBS32 - 0.94) ...

	0.8313	 = Validation score   (accuracy)
	0.35s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	0.8375	 = Validation score   (accuracy)
	0.73s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7812	 = Validation score   (accuracy)
	0.52s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7812	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.7937	 = Validation score   (accuracy)
	3.06s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7375	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.75	 = Validation score   (accuracy)
	0.45s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7188	 = Validation score   (accuracy)
	0.68s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.8063	 = Validation score   (accuracy)
	0.75s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8438	 = Validation score   (accuracy)
	2.49s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.8438	 = Validation score   (accuracy)
	1.92s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 0.8, 'LightGBMLarge': 0.2}
	0.85	 = Validation score   (accuracy)
	0.15s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 12.73s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S25 (SBS32 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S26 (SBS44 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.27 GB / 15.43 GB (53.6%)
Disk Space Avail:   279.97 GB / 459.52 GB (60.9%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S26 (SBS44 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8472.13 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.16s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...

Fitting TabularPredictor for label: S26 (SBS44 - 0.97) ...

	0.6375	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.6312	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...
	0.7312	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.725	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.6937	 = Validation score   (accuracy)
	0.71s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.6875	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: CatBoost ...
	0.7188	 = Validation score   (accuracy)
	4.14s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.6937	 = Validation score   (accuracy)
	0.69s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7063	 = Validation score   (accuracy)
	0.7s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7937	 = Validation score   (accuracy)
	0.89s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.725	 = Validation score   (accuracy)
	1.1s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.7625	 = Validation score   (accuracy)
	4.09s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.6937	 = Validation score   (accuracy)
	1.91s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetFastAI': 0.875, 'RandomForestGini': 0.125}
	0.8	 = Validation score   (accuracy)
	0.19s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 17.09s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S26 (SBS44 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S27 (SBS88 - 0.92)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.37 GB / 15.43 GB (54.2%)
Disk Space Avail:   279.94 GB / 459.52 GB (60.9%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S27 (SBS88 - 0.92)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8570.93 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.12s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.75	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.75	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S27 (SBS88 - 0.92) ...

	0.7875	 = Validation score   (accuracy)
	0.44s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.8	 = Validation score   (accuracy)
	0.65s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7375	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.75	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: CatBoost ...
	0.75	 = Validation score   (accuracy)
	3.97s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7375	 = Validation score   (accuracy)
	0.46s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.725	 = Validation score   (accuracy)
	0.41s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7438	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.75	 = Validation score   (accuracy)
	0.72s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8125	 = Validation score   (accuracy)
	2.01s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.825	 = Validation score   (accuracy)
	1.83s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'LightGBMLarge': 1.0}
	0.825	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 12.74s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S27 (SBS88 - 0.92)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S28 (SBS92 - 0.95)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.52 GB / 15.43 GB (55.2%)
Disk Space Avail:   279.92 GB / 459.52 GB (60.9%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S28 (SBS92 - 0.95)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8725.43 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.2s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.17s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...

Fitting TabularPredictor for label: S28 (SBS92 - 0.95) ...

	0.7375	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.7312	 = Validation score   (accuracy)
	0.02s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...
	0.775	 = Validation score   (accuracy)
	0.47s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ...
	0.775	 = Validation score   (accuracy)
	1.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7562	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.725	 = Validation score   (accuracy)
	0.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.7812	 = Validation score   (accuracy)
	4.93s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7312	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.725	 = Validation score   (accuracy)
	0.43s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7688	 = Validation score   (accuracy)
	0.67s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7875	 = Validation score   (accuracy)
	1.14s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.8187	 = Validation score   (accuracy)
	2.62s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.775	 = Validation score   (accuracy)
	1.69s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 1.0}
	0.8187	 = Validation score   (accuracy)
	0.13s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 15.45s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S28 (SBS92 - 0.95)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ...
AutoGluon will save models to "AutogluonModels/ag-20250407_205054/Predictor_S29 (SBS97 - 0.95)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1726766035~22.04~4092a0e SMP PREEMPT_DYNAMIC Thu S
CPU Count:          8
Memory Avail:       8.49 GB / 15.43 GB (55.1%)
Disk Space Avail:   279.89 GB / 459.52 GB (60.9%)
===================================================
Train Data Rows:    800
Train Data Columns: 96
Label Column:       S29 (SBS97 - 0.95)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    8699.23 MB
	Train Data (Original)  Memory Usage: 0.59 MB (0.0% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.1s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 0.59 MB (0.0% of available memory)
Data preprocessing and feature engineering runtime = 0.13s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.2, Train Rows: 640, Val Rows: 160
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ...
	0.675	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: KNeighborsDist ...
	0.675	 = Validation score   (accuracy)
	0.01s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBMXT ...

Fitting TabularPredictor for label: S29 (SBS97 - 0.95) ...

	0.7812	 = Validation score   (accuracy)
	0.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ...
	0.75	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ...
	0.7	 = Validation score   (accuracy)
	0.49s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: RandomForestEntr ...
	0.7063	 = Validation score   (accuracy)
	0.56s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: CatBoost ...
	0.7812	 = Validation score   (accuracy)
	5.84s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: ExtraTreesGini ...
	0.7125	 = Validation score   (accuracy)
	0.46s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: ExtraTreesEntr ...
	0.7063	 = Validation score   (accuracy)
	0.51s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: NeuralNetFastAI ...
	0.7625	 = Validation score   (accuracy)
	0.81s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: XGBoost ...
	0.7438	 = Validation score   (accuracy)
	1.13s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: NeuralNetTorch ...
	0.7875	 = Validation score   (accuracy)
	1.58s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBMLarge ...
	0.775	 = Validation score   (accuracy)
	1.65s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ...
	Ensemble Weights: {'NeuralNetTorch': 0.833, 'CatBoost': 0.167}
	0.7937	 = Validation score   (accuracy)
	0.14s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 14.83s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20250407_205054/Predictor_S29 (SBS97 - 0.95)")

MultilabelPredictor saved to disk. Load with: MultilabelPredictor.load('AutogluonModels/ag-20250407_205054')
Predicting with TabularPredictor for label: S1 (SBS1 - 0.99) ...
Predicting with TabularPredictor for label: S2 (SBS2 - 0.99) ...
Predicting with TabularPredictor for label: S3 (SBS3 - 0.97) ...
Predicting with TabularPredictor for label: S4 (SBS4 - 0.98) ...
Predicting with TabularPredictor for label: S5 (SBS5 - 0.98) ...
Predicting with TabularPredictor for label: S6 (SBS7a - 1.00) ...
Predicting with TabularPredictor for label: S7 (SBS7b - 0.96) ...
Predicting with TabularPredictor for label: S8 (SBS8 - 0.92) ...
Predicting with TabularPredictor for label: S9 (SBS9 - 0.94) ...
Predicting with TabularPredictor for label: S10 (SBS10a - 1.00) ...
Predicting with TabularPredictor for label: S11 (SBS10d - 0.98) ...
Predicting with TabularPredictor for label: S12 (SBS11 - 0.99) ...
Predicting with TabularPredictor for label: S13 (SBS13 - 0.99) ...
Predicting with TabularPredictor for label: S14 (SBS14 - 0.98) ...
Predicting with TabularPredictor for label: S15 (SBS15 - 0.97) ...
Predicting with TabularPredictor for label: S16 (SBS17 - 0.99) ...
Predicting with TabularPredictor for label: S17 (SBS18 - 0.97) ...
Predicting with TabularPredictor for label: S18 (SBS19 - 0.95) ...
Predicting with TabularPredictor for label: S19 (SBS20 - 0.98) ...
Predicting with TabularPredictor for label: S20 (SBS22 - 0.99) ...
Predicting with TabularPredictor for label: S21 (SBS23 - 0.94) ...
Predicting with TabularPredictor for label: S22 (SBS26 - 0.94) ...
Predicting with TabularPredictor for label: S23 (SBS28 - 0.96) ...
Predicting with TabularPredictor for label: S24 (SBS31 - 0.98) ...
Predicting with TabularPredictor for label: S25 (SBS32 - 0.94) ...
Predicting with TabularPredictor for label: S26 (SBS44 - 0.97) ...
Predicting with TabularPredictor for label: S27 (SBS88 - 0.92) ...
Predicting with TabularPredictor for label: S28 (SBS92 - 0.95) ...
Predicting with TabularPredictor for label: S29 (SBS97 - 0.95) ...

### Final Results

In [ ]:
ml_results_df = pd.DataFrame(columns=['signature', 'best_model', 'accuracy'])
for i in range(len(gt_labels)):
    predictor_class = ml_predictor.get_predictor(gt_labels[i])
    ml_results_df.loc[i, 'signature'] = gt_labels[i]
    ml_results_df.loc[i, 'best_model'] = predictor_class.leaderboard().iloc[0]['model']
    ml_results_df.loc[i, 'accuracy'] = predictor_class.leaderboard().iloc[0]['score_val']
    
    
ml_results_df.head(29)

              signature           best_model accuracy
0      S1 (SBS1 - 0.99)        LightGBMLarge    0.975
1      S2 (SBS2 - 0.99)             LightGBM    0.875
2      S3 (SBS3 - 0.97)  WeightedEnsemble_L2   0.8375
3      S4 (SBS4 - 0.98)  WeightedEnsemble_L2    0.825
4      S5 (SBS5 - 0.98)       NeuralNetTorch  0.90625
5     S6 (SBS7a - 1.00)  WeightedEnsemble_L2   0.9125
6     S7 (SBS7b - 0.96)  WeightedEnsemble_L2  0.81875
7      S8 (SBS8 - 0.92)  WeightedEnsemble_L2  0.85625
8      S9 (SBS9 - 0.94)       NeuralNetTorch   0.8875
9   S10 (SBS10a - 1.00)       NeuralNetTorch    0.875
10  S11 (SBS10d - 0.98)  WeightedEnsemble_L2  0.84375
11   S12 (SBS11 - 0.99)           LightGBMXT    0.825
12   S13 (SBS13 - 0.99)  WeightedEnsemble_L2   0.8625
13   S14 (SBS14 - 0.98)  WeightedEnsemble_L2  0.81875
14   S15 (SBS15 - 0.97)  WeightedEnsemble_L2   0.7875
15   S16 (SBS17 - 0.99)             LightGBM  0.84375
16   S17 (SBS18 - 0.97)  WeightedEnsemble_L2   0.8875
17   S18 (SBS19 - 0.95)       NeuralNetTorch  0.85625
18   S19 (SBS20 - 0.98)      NeuralNetFastAI  0.96875
19   S20 (SBS22 - 0.99)             LightGBM   0.8375
20   S21 (SBS23 - 0.94)       NeuralNetTorch    0.875
21   S22 (SBS26 - 0.94)             LightGBM   0.8875
22   S23 (SBS28 - 0.96)       NeuralNetTorch  0.91875
23   S24 (SBS31 - 0.98)             LightGBM  0.88125
24   S25 (SBS32 - 0.94)  WeightedEnsemble_L2  0.85625
25   S26 (SBS44 - 0.97)  WeightedEnsemble_L2   0.8125
26   S27 (SBS88 - 0.92)  WeightedEnsemble_L2  0.83125
27   S28 (SBS92 - 0.95)       NeuralNetTorch  0.85625
28   S29 (SBS97 - 0.95)  WeightedEnsemble_L2   0.8375

In [ ]:
results_df = pd.DataFrame(columns=['signature', 'best_model', 'accuracy'])
for i in range(len(gt_labels)):
    predictor_class = predictor.get_predictor(gt_labels[i])
    results_df.loc[i, 'signature'] = gt_labels[i]
    results_df.loc[i, 'best_model'] = predictor_class.leaderboard().iloc[0]['model']
    results_df.loc[i, 'accuracy'] = predictor_class.leaderboard().iloc[0]['score_val']
    
    
results_df.head(29)

              signature           best_model accuracy
0      S1 (SBS1 - 0.99)        LightGBMLarge    0.975
1      S2 (SBS2 - 0.99)             LightGBM  0.88125
2      S3 (SBS3 - 0.97)       NeuralNetTorch     0.85
3      S4 (SBS4 - 0.98)  WeightedEnsemble_L2  0.80625
4      S5 (SBS5 - 0.98)  WeightedEnsemble_L2   0.9125
5     S6 (SBS7a - 1.00)  WeightedEnsemble_L2   0.8875
6     S7 (SBS7b - 0.96)       NeuralNetTorch   0.8375
7      S8 (SBS8 - 0.92)  WeightedEnsemble_L2  0.85625
8      S9 (SBS9 - 0.94)       NeuralNetTorch    0.875
9   S10 (SBS10a - 1.00)  WeightedEnsemble_L2    0.875
10  S11 (SBS10d - 0.98)     RandomForestEntr  0.80625
11   S12 (SBS11 - 0.99)       NeuralNetTorch   0.8375
12   S13 (SBS13 - 0.99)  WeightedEnsemble_L2   0.8875
13   S14 (SBS14 - 0.98)  WeightedEnsemble_L2    0.825
14   S15 (SBS15 - 0.97)  WeightedEnsemble_L2     0.75
15   S16 (SBS17 - 0.99)  WeightedEnsemble_L2  0.86875
16   S17 (SBS18 - 0.97)  WeightedEnsemble_L2   0.8625
17   S18 (SBS19 - 0.95)  WeightedEnsemble_L2     0.85
18   S19 (SBS20 - 0.98)      NeuralNetFastAI  0.96875
19   S20 (SBS22 - 0.99)             LightGBM      0.8
20   S21 (SBS23 - 0.94)  WeightedEnsemble_L2  0.89375
21   S22 (SBS26 - 0.94)  WeightedEnsemble_L2      0.9
22   S23 (SBS28 - 0.96)       NeuralNetTorch  0.90625
23   S24 (SBS31 - 0.98)           LightGBMXT      0.9
24   S25 (SBS32 - 0.94)  WeightedEnsemble_L2     0.85
25   S26 (SBS44 - 0.97)  WeightedEnsemble_L2      0.8
26   S27 (SBS88 - 0.92)        LightGBMLarge    0.825
27   S28 (SBS92 - 0.95)       NeuralNetTorch  0.81875
28   S29 (SBS97 - 0.95)  WeightedEnsemble_L2  0.79375

In [ ]:
final_df = pd.DataFrame(columns=['signature', 'best_model', 'accuracy'])
for i in range(len(gt_labels)):
    final_df.loc[i, 'signature'] = gt_labels[i]
    if ml_results_df.iloc[i]['best_model'] == results_df.iloc[i]['best_model']:
        final_df.loc[i, 'best_model'] = ml_results_df.iloc[i]['best_model']
    else:
        final_df.loc[i, 'best_model'] = ml_results_df.iloc[i]['best_model'] + ' vs ' + results_df.iloc[i]['best_model']
    final_df.loc[i, 'accuracy'] = ml_results_df.iloc[i]['accuracy'] - results_df.iloc[i]['accuracy']

In [ ]:
final_df['accuracy'].sum()

0.15624999999999967