In [1]:
import json
import os
import threading
import pandas as pd
import sys
sys.path.append('./')
from utils.MultiLabelPredictor import MultilabelPredictor

/home/massimo/Documents/stage/signature_inference/autogluon/lib/python3.10/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
bin_ground_truth_path = './simulations/ground_truth/bin_exposures.csv'
runs_path = './simulations/data/run_'
data_path = '/trinucleotides_counts_sampling_'
save_evaluation_path = './results/with_tissues_evaluations.json'
tissues_path = './simulations/ground_truth/tumor_site.csv'

In [3]:
bin_gt_df = pd.read_csv(bin_ground_truth_path)
bin_gt_df.head()

,Unnamed: 0,S1 (SBS1 - 0.99),S2 (SBS2 - 0.99),S3 (SBS3 - 0.97),S4 (SBS4 - 0.98),S5 (SBS5 - 0.98),S6 (SBS7a - 1.00),S7 (SBS7b - 0.96),S8 (SBS8 - 0.92),S9 (SBS9 - 0.94),...,S20 (SBS22 - 0.99),S21 (SBS23 - 0.94),S22 (SBS26 - 0.94),S23 (SBS28 - 0.96),S24 (SBS31 - 0.98),S25 (SBS32 - 0.94),S26 (SBS44 - 0.97),S27 (SBS88 - 0.92),S28 (SBS92 - 0.95),S29 (SBS97 - 0.95)
0,0009b464-b376-4fbc-8a56-da538269a02f,True,True,True,True,True,True,False,True,False,...,True,False,False,False,True,True,False,False,False,False
1,00493087-9d9d-40ca-86d5-936f1b951c93,True,False,False,False,True,False,False,False,False,...,False,True,True,False,False,False,False,True,False,False
2,00508f2b-36bf-44fc-b66b-97e1f3e40bfa,True,True,False,True,True,True,True,False,False,...,False,False,False,False,False,False,False,True,False,False
3,005794f1-5a87-45b5-9811-83ddf6924568,True,True,True,True,True,True,True,True,False,...,True,True,False,True,False,True,False,False,True,False
4,005e85a3-3571-462d-8dc9-2babfc7ace21,True,False,False,False,True,True,False,False,False,...,False,False,False,False,False,True,True,False,False,False

In [4]:
tissues_df = pd.read_csv(tissues_path)
tissues_df.head()

                             Unnamed: 0                   Organ Cohort
0  0009b464-b376-4fbc-8a56-da538269a02f                   Ovary   ICGC
1  00493087-9d9d-40ca-86d5-936f1b951c93  Central Nervous System   ICGC
2  00508f2b-36bf-44fc-b66b-97e1f3e40bfa   Neuroendocrine Tumors   ICGC
3  005794f1-5a87-45b5-9811-83ddf6924568                  Kidney   ICGC
4  005e85a3-3571-462d-8dc9-2babfc7ace21                Prostate   ICGC

In [5]:
data_df = pd.read_csv('./simulations/data/run_1/trinucleotides_counts_sampling_0.1.csv')
data_df.head()

,Unnamed: 0,A[C>A]A,A[C>A]C,A[C>A]G,A[C>A]T,A[C>G]A,A[C>G]C,A[C>G]G,A[C>G]T,A[C>T]A,...,T[T>A]G,T[T>A]T,T[T>C]A,T[T>C]C,T[T>C]G,T[T>C]T,T[T>G]A,T[T>G]C,T[T>G]G,T[T>G]T
0,0009b464-b376-4fbc-8a56-da538269a02f,38,36,4,28,17,7,4,16,25,...,4,14,13,12,2,14,7,8,3,12
1,00493087-9d9d-40ca-86d5-936f1b951c93,3,5,0,2,3,0,0,1,5,...,1,3,2,2,4,3,0,0,0,2
2,00508f2b-36bf-44fc-b66b-97e1f3e40bfa,5,4,1,0,0,0,0,0,6,...,1,1,3,0,3,5,1,0,0,0
3,005794f1-5a87-45b5-9811-83ddf6924568,22,5,0,11,8,1,1,5,9,...,4,10,2,1,4,3,3,3,6,8
4,005e85a3-3571-462d-8dc9-2babfc7ace21,0,0,0,5,0,0,0,1,7,...,0,2,0,1,0,4,2,1,1,1

In [6]:
df = pd.merge(data_df, bin_gt_df, on='Unnamed: 0')
df.head()

,Unnamed: 0,A[C>A]A,A[C>A]C,A[C>A]G,A[C>A]T,A[C>G]A,A[C>G]C,A[C>G]G,A[C>G]T,A[C>T]A,...,S20 (SBS22 - 0.99),S21 (SBS23 - 0.94),S22 (SBS26 - 0.94),S23 (SBS28 - 0.96),S24 (SBS31 - 0.98),S25 (SBS32 - 0.94),S26 (SBS44 - 0.97),S27 (SBS88 - 0.92),S28 (SBS92 - 0.95),S29 (SBS97 - 0.95)
0,0009b464-b376-4fbc-8a56-da538269a02f,38,36,4,28,17,7,4,16,25,...,True,False,False,False,True,True,False,False,False,False
1,00493087-9d9d-40ca-86d5-936f1b951c93,3,5,0,2,3,0,0,1,5,...,False,True,True,False,False,False,False,True,False,False
2,00508f2b-36bf-44fc-b66b-97e1f3e40bfa,5,4,1,0,0,0,0,0,6,...,False,False,False,False,False,False,False,True,False,False
3,005794f1-5a87-45b5-9811-83ddf6924568,22,5,0,11,8,1,1,5,9,...,True,True,False,True,False,True,False,False,True,False
4,005e85a3-3571-462d-8dc9-2babfc7ace21,0,0,0,5,0,0,0,1,7,...,False,False,False,False,False,True,True,False,False,False

In [7]:
train_df = df.sample(frac=0.8, random_state=0)
test_df = df.drop(train_df.index)
print(train_df.shape)
train_df.head()

(14495, 126)

,Unnamed: 0,A[C>A]A,A[C>A]C,A[C>A]G,A[C>A]T,A[C>G]A,A[C>G]C,A[C>G]G,A[C>G]T,A[C>T]A,...,S20 (SBS22 - 0.99),S21 (SBS23 - 0.94),S22 (SBS26 - 0.94),S23 (SBS28 - 0.96),S24 (SBS31 - 0.98),S25 (SBS32 - 0.94),S26 (SBS44 - 0.97),S27 (SBS88 - 0.92),S28 (SBS92 - 0.95),S29 (SBS97 - 0.95)
16885,HMF003210A,3,1,0,1,0,1,1,3,3,...,False,False,False,False,False,True,False,True,False,False
6591,GEL-2361061-11,2,1,0,2,0,1,0,1,9,...,False,False,False,False,False,False,True,False,False,False
3639,GEL-2111089-11,7,5,1,6,3,1,0,4,5,...,True,False,False,False,False,True,False,True,True,False
11456,GEL-2764583-11,5,3,2,6,8,0,4,3,10,...,True,False,False,False,False,True,False,True,True,True
13818,GEL-2964830-11,14,13,0,7,15,2,0,4,15,...,False,False,False,False,False,False,False,True,False,False

In [8]:
print(test_df.shape)
test_df.head()

(3624, 126)

,Unnamed: 0,A[C>A]A,A[C>A]C,A[C>A]G,A[C>A]T,A[C>G]A,A[C>G]C,A[C>G]G,A[C>G]T,A[C>T]A,...,S20 (SBS22 - 0.99),S21 (SBS23 - 0.94),S22 (SBS26 - 0.94),S23 (SBS28 - 0.96),S24 (SBS31 - 0.98),S25 (SBS32 - 0.94),S26 (SBS44 - 0.97),S27 (SBS88 - 0.92),S28 (SBS92 - 0.95),S29 (SBS97 - 0.95)
2,00508f2b-36bf-44fc-b66b-97e1f3e40bfa,5,4,1,0,0,0,0,0,6,...,False,False,False,False,False,False,False,True,False,False
3,005794f1-5a87-45b5-9811-83ddf6924568,22,5,0,11,8,1,1,5,9,...,True,True,False,True,False,True,False,False,True,False
10,00c27940-c623-11e3-bf01-24c6515278c0,56,20,10,18,9,3,0,6,27,...,False,False,True,False,False,False,True,True,True,True
19,01dc6872-c623-11e3-bf01-24c6515278c0,19,6,1,11,4,2,1,6,23,...,False,False,True,False,True,False,False,True,True,True
27,030695f6-c623-11e3-bf01-24c6515278c0,22,16,5,12,9,7,1,9,20,...,False,False,True,False,True,False,False,True,True,True

In [9]:
labels = bin_gt_df.columns[1:]
problem_type = ['binary'] * len(labels)
time_limit = 5
# Create the model
predictor = MultilabelPredictor(labels=labels, problem_types=problem_type)
predictor.fit(train_df, time_limit=time_limit)

No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S1 (SBS1 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.95 GB / 15.43 GB (64.5%)
Disk Space Avail:   72.65 GB / 459.52 GB (15.8%)
===================================================
Train Data Rows:    14495
Train Data Columns: 97
Label Column:       S1 (SBS1 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...

Fitting TabularPredictor for label: S1 (SBS1 - 0.99) ...

	Available Memory:                    10173.86 MB
	Train Data (Original)  Memory Usage: 11.62 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', []) : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	0.2s = Fit runtime
	96 features in original data used to generate 96 features in processed data.
	Train Data (Processed) Memory Usage: 10.62 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.75s of the 4.75s of remaining time.
	0.9697	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.64s of the 4.64s of remaining time.
	0.9703	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.54s of the 4.54s of remaining time.
	0.9745	 = Validation score   (accuracy)
	1.0s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 3.53s of the 3.53s of remaining time.
	0.9717	 = Validation score   (accuracy)
	2.06s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 1.44s of the 1.44s of remaining time.
	0.9724	 = Validation score   (accuracy)
	3.02s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.75s of the -1.66s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.9745	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 6.74s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S1 (SBS1 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S2 (SBS2 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.85 GB / 15.43 GB (63.8%)
Disk Space Avail:   72.62 GB / 459.52 GB (15.8%)
===================================================
Train Data Rows:    14495
Train Data Columns: 98
Label Column:       S2 (SBS2 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10098.51 MB
	Train Data (Original)  Memory Usage: 11.64 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 1 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  1 | ['S1 (SBS1 - 0.99)']
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  1 | ['S1 (SBS1 - 0.99)']
	0.2s = Fit runtime
	97 features in original data used to generate 97 features in processed data.
	Train Data (Processed) Memory Usage: 10.63 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.19s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()

Fitting TabularPredictor for label: S2 (SBS2 - 0.99) ...

Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.81s of the 4.81s of remaining time.
	0.8883	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.71s of the 4.71s of remaining time.
	0.8883	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.61s of the 4.61s of remaining time.
	0.9097	 = Validation score   (accuracy)
	1.97s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.6s of the 2.6s of remaining time.
	0.9152	 = Validation score   (accuracy)
	2.25s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.32s of the 0.32s of remaining time.
	0.8972	 = Validation score   (accuracy)
	3.57s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.81s of the -3.36s of remaining time.
	Ensemble Weights: {'LightGBM': 0.5, 'KNeighborsUnif': 0.25, 'RandomForestGini': 0.25}
	0.9193	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 8.43s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S2 (SBS2 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S3 (SBS3 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.78 GB / 15.43 GB (63.4%)
Disk Space Avail:   72.56 GB / 459.52 GB (15.8%)
===================================================
Train Data Rows:    14495
Train Data Columns: 99
Label Column:       S3 (SBS3 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10021.54 MB
	Train Data (Original)  Memory Usage: 11.65 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 2 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  2 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)']
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  2 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)']
	0.2s = Fit runtime
	98 features in original data used to generate 98 features in processed data.
	Train Data (Processed) Memory Usage: 10.64 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.19s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()

Fitting TabularPredictor for label: S3 (SBS3 - 0.97) ...

Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.81s of the 4.81s of remaining time.
	0.7772	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.68s of the 4.68s of remaining time.
	0.7772	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.56s of the 4.56s of remaining time.
	0.829	 = Validation score   (accuracy)
	1.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.8s of the 2.8s of remaining time.
	0.8234	 = Validation score   (accuracy)
	2.59s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.17s of the 0.17s of remaining time.
	0.8152	 = Validation score   (accuracy)
	3.83s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.81s of the -3.8s of remaining time.
	Ensemble Weights: {'KNeighborsDist': 0.375, 'LightGBMXT': 0.312, 'LightGBM': 0.25, 'RandomForestGini': 0.062}
	0.84	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 8.87s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S3 (SBS3 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S4 (SBS4 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.70 GB / 15.43 GB (62.9%)
Disk Space Avail:   72.47 GB / 459.52 GB (15.8%)
===================================================
Train Data Rows:    14495
Train Data Columns: 100
Label Column:       S4 (SBS4 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9943.01 MB
	Train Data (Original)  Memory Usage: 11.67 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 3 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  3 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)']
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  3 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)']
	0.2s = Fit runtime
	99 features in original data used to generate 99 features in processed data.
	Train Data (Processed) Memory Usage: 10.66 MB (0.1% of available memory)

Fitting TabularPredictor for label: S4 (SBS4 - 0.98) ...

Data preprocessing and feature engineering runtime = 0.19s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.81s of the 4.8s of remaining time.
	0.6883	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.68s of the 4.68s of remaining time.
	0.6883	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.56s of the 4.56s of remaining time.
	0.7669	 = Validation score   (accuracy)
	2.25s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.25s of the 2.25s of remaining time.
	Ran out of time, early stopping on iteration 617. Best iteration is:
	[593]	valid_set's binary_error: 0.236552
	0.7634	 = Validation score   (accuracy)
	2.31s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.81s of the -0.12s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.7669	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S4 (SBS4 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S5 (SBS5 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.80 GB / 15.43 GB (63.5%)
Disk Space Avail:   72.44 GB / 459.52 GB (15.8%)
===================================================
Train Data Rows:    14495
Train Data Columns: 101
Label Column:       S5 (SBS5 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10047.67 MB
	Train Data (Original)  Memory Usage: 11.68 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 4 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  4 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)']

Fitting TabularPredictor for label: S5 (SBS5 - 0.98) ...

		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  4 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)']
	0.2s = Fit runtime
	100 features in original data used to generate 100 features in processed data.
	Train Data (Processed) Memory Usage: 10.67 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.21s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.79s of the 4.79s of remaining time.
	0.8772	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.67s of the 4.67s of remaining time.
	0.8779	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.53s of the 4.53s of remaining time.
	0.9041	 = Validation score   (accuracy)
	1.39s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 3.11s of the 3.1s of remaining time.
	0.8952	 = Validation score   (accuracy)
	1.34s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 1.76s of the 1.76s of remaining time.
	0.8897	 = Validation score   (accuracy)
	3.92s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.79s of the -2.27s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.833, 'LightGBM': 0.167}
	0.9048	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 7.35s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S5 (SBS5 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S6 (SBS7a - 1.00)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.80 GB / 15.43 GB (63.5%)
Disk Space Avail:   72.38 GB / 459.52 GB (15.8%)
===================================================
Train Data Rows:    14495
Train Data Columns: 102
Label Column:       S6 (SBS7a - 1.00)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10047.32 MB
	Train Data (Original)  Memory Usage: 11.69 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 5 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):

Fitting TabularPredictor for label: S6 (SBS7a - 1.00) ...

		('bool', []) :  5 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)']
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  5 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)']
	0.2s = Fit runtime
	101 features in original data used to generate 101 features in processed data.
	Train Data (Processed) Memory Usage: 10.69 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.21s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.79s of the 4.79s of remaining time.
	0.8179	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.67s of the 4.67s of remaining time.
	0.8179	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.55s of the 4.55s of remaining time.
	0.849	 = Validation score   (accuracy)
	1.27s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 3.26s of the 3.26s of remaining time.
	0.8517	 = Validation score   (accuracy)
	2.24s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.98s of the 0.97s of remaining time.
	0.8393	 = Validation score   (accuracy)
	4.52s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.79s of the -3.66s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.8517	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 8.74s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S6 (SBS7a - 1.00)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S7 (SBS7b - 0.96)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.84 GB / 15.43 GB (63.8%)
Disk Space Avail:   72.30 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 103
Label Column:       S7 (SBS7b - 0.96)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10081.62 MB
	Train Data (Original)  Memory Usage: 11.71 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 6 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  6 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  6 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]

Fitting TabularPredictor for label: S7 (SBS7b - 0.96) ...

	0.2s = Fit runtime
	102 features in original data used to generate 102 features in processed data.
	Train Data (Processed) Memory Usage: 10.70 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.2s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.8s of the 4.8s of remaining time.
	0.7248	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.67s of the 4.67s of remaining time.
	0.7241	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.57s of the 4.57s of remaining time.
	0.7772	 = Validation score   (accuracy)
	2.35s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.16s of the 2.16s of remaining time.
	Ran out of time, early stopping on iteration 598. Best iteration is:
	[482]	valid_set's binary_error: 0.209655
	0.7903	 = Validation score   (accuracy)
	2.21s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.8s of the -0.1s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.7903	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.17s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S7 (SBS7b - 0.96)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S8 (SBS8 - 0.92)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.83 GB / 15.43 GB (63.7%)
Disk Space Avail:   72.27 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 104
Label Column:       S8 (SBS8 - 0.92)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10078.31 MB
	Train Data (Original)  Memory Usage: 11.72 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 7 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  7 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  7 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	103 features in original data used to generate 103 features in processed data.

Fitting TabularPredictor for label: S8 (SBS8 - 0.92) ...

	Train Data (Processed) Memory Usage: 10.71 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.2s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.8s of the 4.8s of remaining time.
	0.7221	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.68s of the 4.67s of remaining time.
	0.7228	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.56s of the 4.55s of remaining time.

[1000]	valid_set's binary_error: 0.202759

	Ran out of time, early stopping on iteration 2011. Best iteration is:
	[1758]	valid_set's binary_error: 0.193793

[2000]	valid_set's binary_error: 0.19931

	0.8062	 = Validation score   (accuracy)
	4.66s	 = Training   runtime
	0.05s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.8s of the -0.26s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.933, 'KNeighborsDist': 0.067}
	0.8069	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.33s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S8 (SBS8 - 0.92)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S9 (SBS9 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.79 GB / 15.43 GB (63.5%)
Disk Space Avail:   72.25 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 105
Label Column:       S9 (SBS9 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10039.20 MB
	Train Data (Original)  Memory Usage: 11.73 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 8 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...

Fitting TabularPredictor for label: S9 (SBS9 - 0.94) ...

	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  8 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  8 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	104 features in original data used to generate 104 features in processed data.
	Train Data (Processed) Memory Usage: 10.73 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.22s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.78s of the 4.77s of remaining time.
	0.7503	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.67s of the 4.67s of remaining time.
	0.7503	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.55s of the 4.55s of remaining time.
	0.8345	 = Validation score   (accuracy)
	2.81s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 1.67s of the 1.67s of remaining time.

[1000]	valid_set's binary_error: 0.167586

	Ran out of time, early stopping on iteration 392. Best iteration is:
	[210]	valid_set's binary_error: 0.166207
	0.8338	 = Validation score   (accuracy)
	1.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.78s of the -0.09s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.833, 'LightGBM': 0.167}
	0.8352	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.17s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S9 (SBS9 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S10 (SBS10a - 1.00)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.81 GB / 15.43 GB (63.6%)
Disk Space Avail:   72.22 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 106
Label Column:       S10 (SBS10a - 1.00)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10061.06 MB
	Train Data (Original)  Memory Usage: 11.75 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 9 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S10 (SBS10a - 1.00) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) :  9 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) :  9 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	105 features in original data used to generate 105 features in processed data.
	Train Data (Processed) Memory Usage: 10.74 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.75s of the 4.75s of remaining time.
	0.7434	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.65s of the 4.65s of remaining time.
	0.7434	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.53s of the 4.52s of remaining time.

[1000]	valid_set's binary_error: 0.188966

	0.8145	 = Validation score   (accuracy)
	3.91s	 = Training   runtime
	0.04s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 0.52s of the 0.51s of remaining time.
	Ran out of time, early stopping on iteration 82. Best iteration is:
	[59]	valid_set's binary_error: 0.211724
	0.7883	 = Validation score   (accuracy)
	0.55s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.75s of the -0.07s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.8145	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.17s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S10 (SBS10a - 1.00)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S11 (SBS10d - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.84 GB / 15.43 GB (63.8%)
Disk Space Avail:   72.19 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 107
Label Column:       S11 (SBS10d - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10084.86 MB
	Train Data (Original)  Memory Usage: 11.76 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 10 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S11 (SBS10d - 0.98) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 10 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 10 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	106 features in original data used to generate 106 features in processed data.
	Train Data (Processed) Memory Usage: 10.75 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.24s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.76s of the 4.76s of remaining time.
	0.7	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.65s of the 4.65s of remaining time.
	0.7	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.1s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.5s of the 4.5s of remaining time.
	0.7628	 = Validation score   (accuracy)
	1.72s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.75s of the 2.74s of remaining time.
	0.7614	 = Validation score   (accuracy)
	2.18s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.54s of the 0.54s of remaining time.
	0.7497	 = Validation score   (accuracy)
	4.24s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.76s of the -3.88s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.7628	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 8.98s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S11 (SBS10d - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S12 (SBS11 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.83 GB / 15.43 GB (63.7%)
Disk Space Avail:   72.10 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 108
Label Column:       S12 (SBS11 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10080.24 MB
	Train Data (Original)  Memory Usage: 11.78 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 11 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...

Fitting TabularPredictor for label: S12 (SBS11 - 0.99) ...

	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 11 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 11 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	107 features in original data used to generate 107 features in processed data.
	Train Data (Processed) Memory Usage: 10.77 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.23s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.77s of the 4.77s of remaining time.
	0.7648	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.64s of the 4.64s of remaining time.
	0.7655	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.54s of the 4.54s of remaining time.
	0.8076	 = Validation score   (accuracy)
	1.77s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.73s of the 2.73s of remaining time.
	0.8186	 = Validation score   (accuracy)
	1.74s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.97s of the 0.97s of remaining time.
	0.7917	 = Validation score   (accuracy)
	4.17s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.77s of the -3.41s of remaining time.
	Ensemble Weights: {'LightGBM': 0.714, 'RandomForestGini': 0.214, 'KNeighborsUnif': 0.071}
	0.8221	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 8.52s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S12 (SBS11 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S13 (SBS13 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.83 GB / 15.43 GB (63.7%)
Disk Space Avail:   72.01 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 109
Label Column:       S13 (SBS13 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10064.49 MB
	Train Data (Original)  Memory Usage: 11.79 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 12 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S13 (SBS13 - 0.99) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 12 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 12 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	108 features in original data used to generate 108 features in processed data.
	Train Data (Processed) Memory Usage: 10.78 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.24s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.76s of the 4.76s of remaining time.
	0.8262	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.66s of the 4.66s of remaining time.
	0.8255	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.56s of the 4.56s of remaining time.
	0.871	 = Validation score   (accuracy)
	2.85s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 1.67s of the 1.67s of remaining time.
	Ran out of time, early stopping on iteration 365. Best iteration is:
	[181]	valid_set's binary_error: 0.123448
	0.8766	 = Validation score   (accuracy)
	1.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.76s of the -0.1s of remaining time.
	Ensemble Weights: {'LightGBM': 0.783, 'LightGBMXT': 0.217}
	0.8779	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S13 (SBS13 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S14 (SBS14 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.85 GB / 15.43 GB (63.8%)
Disk Space Avail:   71.99 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 110
Label Column:       S14 (SBS14 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10087.17 MB
	Train Data (Original)  Memory Usage: 11.80 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 13 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S14 (SBS14 - 0.98) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 13 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 13 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	109 features in original data used to generate 109 features in processed data.
	Train Data (Processed) Memory Usage: 10.80 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.75s of the 4.75s of remaining time.
	0.76	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.64s of the 4.64s of remaining time.
	0.7593	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.52s of the 4.52s of remaining time.
	0.8131	 = Validation score   (accuracy)
	2.6s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 1.88s of the 1.87s of remaining time.
	0.8028	 = Validation score   (accuracy)
	1.89s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.75s of the -0.05s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.8131	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.15s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S14 (SBS14 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S15 (SBS15 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.87 GB / 15.43 GB (64.0%)
Disk Space Avail:   71.96 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 111
Label Column:       S15 (SBS15 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10110.73 MB
	Train Data (Original)  Memory Usage: 11.82 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 14 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S15 (SBS15 - 0.97) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 14 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 14 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	110 features in original data used to generate 110 features in processed data.
	Train Data (Processed) Memory Usage: 10.81 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.75s of the 4.75s of remaining time.
	0.6862	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.63s of the 4.63s of remaining time.
	0.6869	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.5s of the 4.5s of remaining time.
	0.7752	 = Validation score   (accuracy)
	2.3s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.15s of the 2.15s of remaining time.
	Ran out of time, early stopping on iteration 531. Best iteration is:
	[531]	valid_set's binary_error: 0.214483
	0.7855	 = Validation score   (accuracy)
	2.21s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.75s of the -0.12s of remaining time.
	Ensemble Weights: {'LightGBM': 0.714, 'LightGBMXT': 0.214, 'KNeighborsUnif': 0.071}
	0.789	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.21s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S15 (SBS15 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S16 (SBS17 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.82 GB / 15.43 GB (63.6%)
Disk Space Avail:   71.94 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 112
Label Column:       S16 (SBS17 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10051.11 MB
	Train Data (Original)  Memory Usage: 11.83 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 15 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S16 (SBS17 - 0.99) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 15 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 15 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	111 features in original data used to generate 111 features in processed data.
	Train Data (Processed) Memory Usage: 10.82 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.26s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.74s of the 4.74s of remaining time.
	0.7207	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.64s of the 4.64s of remaining time.
	0.7207	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.53s of the 4.53s of remaining time.
	0.8138	 = Validation score   (accuracy)
	3.29s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 1.19s of the 1.19s of remaining time.
	Ran out of time, early stopping on iteration 240. Best iteration is:
	[181]	valid_set's binary_error: 0.178621
	0.8214	 = Validation score   (accuracy)
	1.23s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.74s of the -0.08s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.8214	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.17s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S16 (SBS17 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S17 (SBS18 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.81 GB / 15.43 GB (63.6%)
Disk Space Avail:   71.92 GB / 459.52 GB (15.7%)
===================================================
Train Data Rows:    14495
Train Data Columns: 113
Label Column:       S17 (SBS18 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10045.52 MB
	Train Data (Original)  Memory Usage: 11.84 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 16 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S17 (SBS18 - 0.97) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 16 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 16 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	112 features in original data used to generate 112 features in processed data.
	Train Data (Processed) Memory Usage: 10.84 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.75s of the 4.74s of remaining time.
	0.731	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.62s of the 4.62s of remaining time.
	0.731	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.5s of the 4.5s of remaining time.
	0.8234	 = Validation score   (accuracy)
	2.41s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.03s of the 2.03s of remaining time.
	0.8159	 = Validation score   (accuracy)
	1.72s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.29s of the 0.29s of remaining time.
	0.7979	 = Validation score   (accuracy)
	3.96s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.75s of the -3.87s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.636, 'LightGBM': 0.273, 'KNeighborsUnif': 0.091}
	0.8297	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 8.97s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S17 (SBS18 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S18 (SBS19 - 0.95)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.85 GB / 15.43 GB (63.8%)
Disk Space Avail:   71.82 GB / 459.52 GB (15.6%)
===================================================
Train Data Rows:    14495
Train Data Columns: 114
Label Column:       S18 (SBS19 - 0.95)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10099.61 MB
	Train Data (Original)  Memory Usage: 11.86 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 17 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S18 (SBS19 - 0.95) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 17 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 17 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	113 features in original data used to generate 113 features in processed data.
	Train Data (Processed) Memory Usage: 10.85 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.75s of the 4.75s of remaining time.
	0.7172	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.65s of the 4.64s of remaining time.
	0.7172	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.54s of the 4.54s of remaining time.
	0.7759	 = Validation score   (accuracy)
	1.45s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 3.06s of the 3.06s of remaining time.
	0.7648	 = Validation score   (accuracy)
	1.53s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 1.51s of the 1.51s of remaining time.
	0.7434	 = Validation score   (accuracy)
	4.13s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.75s of the -2.79s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.7759	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 7.88s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S18 (SBS19 - 0.95)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S19 (SBS20 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.76 GB / 15.43 GB (63.2%)
Disk Space Avail:   71.73 GB / 459.52 GB (15.6%)
===================================================
Train Data Rows:    14495
Train Data Columns: 115
Label Column:       S19 (SBS20 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10003.81 MB
	Train Data (Original)  Memory Usage: 11.87 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 18 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S19 (SBS20 - 0.98) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 18 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 18 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	114 features in original data used to generate 114 features in processed data.
	Train Data (Processed) Memory Usage: 10.87 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.75s of the 4.75s of remaining time.
	0.9545	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.64s of the 4.64s of remaining time.
	0.9545	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.54s of the 4.54s of remaining time.
	0.9641	 = Validation score   (accuracy)
	1.2s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 3.32s of the 3.32s of remaining time.
	0.9614	 = Validation score   (accuracy)
	1.53s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 1.78s of the 1.77s of remaining time.
	0.9579	 = Validation score   (accuracy)
	3.18s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.75s of the -1.56s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.9641	 = Validation score   (accuracy)
	0.05s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 6.64s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S19 (SBS20 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S20 (SBS22 - 0.99)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.87 GB / 15.43 GB (63.9%)
Disk Space Avail:   71.69 GB / 459.52 GB (15.6%)
===================================================
Train Data Rows:    14495
Train Data Columns: 116
Label Column:       S20 (SBS22 - 0.99)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10112.79 MB
	Train Data (Original)  Memory Usage: 11.89 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 19 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...

Fitting TabularPredictor for label: S20 (SBS22 - 0.99) ...

			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 19 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 19 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	115 features in original data used to generate 115 features in processed data.
	Train Data (Processed) Memory Usage: 10.88 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.28s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.72s of the 4.72s of remaining time.
	0.6917	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.59s of the 4.59s of remaining time.
	0.6924	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.47s of the 4.47s of remaining time.
	0.7848	 = Validation score   (accuracy)
	2.31s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.11s of the 2.11s of remaining time.
	Ran out of time, early stopping on iteration 468. Best iteration is:
	[282]	valid_set's binary_error: 0.208276
	0.7917	 = Validation score   (accuracy)
	2.16s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.72s of the -0.09s of remaining time.
	Ensemble Weights: {'LightGBM': 1.0}
	0.7917	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.2s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S20 (SBS22 - 0.99)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S21 (SBS23 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.85 GB / 15.43 GB (63.8%)
Disk Space Avail:   71.66 GB / 459.52 GB (15.6%)
===================================================
Train Data Rows:    14495
Train Data Columns: 117
Label Column:       S21 (SBS23 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10081.48 MB
	Train Data (Original)  Memory Usage: 11.90 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 20 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...

Fitting TabularPredictor for label: S21 (SBS23 - 0.94) ...

		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 20 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 20 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.3s = Fit runtime
	116 features in original data used to generate 116 features in processed data.
	Train Data (Processed) Memory Usage: 10.89 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.3s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.7s of the 4.7s of remaining time.
	0.84	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.57s of the 4.57s of remaining time.
	0.8393	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.45s of the 4.44s of remaining time.
	0.8697	 = Validation score   (accuracy)
	1.87s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.53s of the 2.53s of remaining time.
	0.8641	 = Validation score   (accuracy)
	1.52s	 = Training   runtime
	0.0s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 1.0s of the 1.0s of remaining time.
	0.8517	 = Validation score   (accuracy)
	3.56s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.7s of the -2.76s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.818, 'KNeighborsUnif': 0.182}
	0.8731	 = Validation score   (accuracy)
	0.07s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 7.87s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S21 (SBS23 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S22 (SBS26 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.80 GB / 15.43 GB (63.5%)
Disk Space Avail:   71.59 GB / 459.52 GB (15.6%)
===================================================
Train Data Rows:    14495
Train Data Columns: 118
Label Column:       S22 (SBS26 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10045.97 MB
	Train Data (Original)  Memory Usage: 11.91 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 21 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S22 (SBS26 - 0.94) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 21 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 21 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	117 features in original data used to generate 117 features in processed data.
	Train Data (Processed) Memory Usage: 10.91 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.26s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.74s of the 4.74s of remaining time.
	0.8441	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.63s of the 4.63s of remaining time.
	0.8441	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.53s of the 4.53s of remaining time.

[1000]	valid_set's binary_error: 0.114483

	0.8903	 = Validation score   (accuracy)
	2.93s	 = Training   runtime
	0.03s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 1.52s of the 1.52s of remaining time.
	Ran out of time, early stopping on iteration 320. Best iteration is:
	[297]	valid_set's binary_error: 0.123448
	0.8766	 = Validation score   (accuracy)
	1.57s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.74s of the -0.09s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.8903	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.19s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S22 (SBS26 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S23 (SBS28 - 0.96)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.81 GB / 15.43 GB (63.6%)
Disk Space Avail:   71.56 GB / 459.52 GB (15.6%)
===================================================
Train Data Rows:    14495
Train Data Columns: 119
Label Column:       S23 (SBS28 - 0.96)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10061.12 MB
	Train Data (Original)  Memory Usage: 11.93 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 22 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...

Fitting TabularPredictor for label: S23 (SBS28 - 0.96) ...

	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 22 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 22 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.3s = Fit runtime
	118 features in original data used to generate 118 features in processed data.
	Train Data (Processed) Memory Usage: 10.92 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.3s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.7s of the 4.7s of remaining time.
	0.8331	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.09s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.57s of the 4.57s of remaining time.
	0.8338	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.45s of the 4.45s of remaining time.
	0.8621	 = Validation score   (accuracy)
	1.61s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.81s of the 2.81s of remaining time.
	Ran out of time, early stopping on iteration 661. Best iteration is:
	[521]	valid_set's binary_error: 0.126207
	0.8738	 = Validation score   (accuracy)
	2.87s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.7s of the -0.12s of remaining time.
	Ensemble Weights: {'LightGBM': 0.636, 'KNeighborsUnif': 0.182, 'LightGBMXT': 0.182}
	0.8752	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.22s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S23 (SBS28 - 0.96)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S24 (SBS31 - 0.98)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.83 GB / 15.43 GB (63.7%)
Disk Space Avail:   71.54 GB / 459.52 GB (15.6%)
===================================================
Train Data Rows:    14495
Train Data Columns: 120
Label Column:       S24 (SBS31 - 0.98)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10067.92 MB
	Train Data (Original)  Memory Usage: 11.94 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 23 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S24 (SBS31 - 0.98) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 23 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 23 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	119 features in original data used to generate 119 features in processed data.
	Train Data (Processed) Memory Usage: 10.93 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.27s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.73s of the 4.73s of remaining time.
	0.911	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.61s of the 4.61s of remaining time.
	0.911	 = Validation score   (accuracy)
	0.04s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.51s of the 4.51s of remaining time.
	0.9276	 = Validation score   (accuracy)
	1.34s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 3.15s of the 3.14s of remaining time.
	0.9241	 = Validation score   (accuracy)
	2.19s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.93s of the 0.93s of remaining time.
	0.9138	 = Validation score   (accuracy)
	3.42s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.73s of the -2.61s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.571, 'LightGBM': 0.286, 'KNeighborsDist': 0.143}
	0.9297	 = Validation score   (accuracy)
	0.08s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 7.74s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S24 (SBS31 - 0.98)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S25 (SBS32 - 0.94)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.83 GB / 15.43 GB (63.7%)
Disk Space Avail:   71.48 GB / 459.52 GB (15.6%)
===================================================
Train Data Rows:    14495
Train Data Columns: 121
Label Column:       S25 (SBS32 - 0.94)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10080.08 MB
	Train Data (Original)  Memory Usage: 11.96 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 24 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S25 (SBS32 - 0.94) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 24 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 24 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	120 features in original data used to generate 120 features in processed data.
	Train Data (Processed) Memory Usage: 10.95 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.26s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.74s of the 4.74s of remaining time.
	0.7283	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.64s of the 4.64s of remaining time.
	0.7276	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.54s of the 4.53s of remaining time.
	0.7979	 = Validation score   (accuracy)
	2.1s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.39s of the 2.39s of remaining time.
	Ran out of time, early stopping on iteration 548. Best iteration is:
	[508]	valid_set's binary_error: 0.203448
	0.7966	 = Validation score   (accuracy)
	2.45s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.74s of the -0.13s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.958, 'LightGBM': 0.042}
	0.7993	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.23s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S25 (SBS32 - 0.94)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S26 (SBS44 - 0.97)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.83 GB / 15.43 GB (63.7%)
Disk Space Avail:   71.45 GB / 459.52 GB (15.5%)
===================================================
Train Data Rows:    14495
Train Data Columns: 122
Label Column:       S26 (SBS44 - 0.97)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10064.83 MB
	Train Data (Original)  Memory Usage: 11.97 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 25 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...

Fitting TabularPredictor for label: S26 (SBS44 - 0.97) ...

			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...
	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 25 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 25 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	121 features in original data used to generate 121 features in processed data.
	Train Data (Processed) Memory Usage: 10.96 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.28s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.72s of the 4.72s of remaining time.
	0.7007	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.08s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.6s of the 4.6s of remaining time.
	0.7007	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.5s of the 4.5s of remaining time.
	0.7572	 = Validation score   (accuracy)
	1.33s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 3.15s of the 3.15s of remaining time.
	0.7683	 = Validation score   (accuracy)
	2.31s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.81s of the 0.81s of remaining time.
	0.7407	 = Validation score   (accuracy)
	4.43s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.72s of the -3.79s of remaining time.
	Ensemble Weights: {'LightGBM': 0.9, 'LightGBMXT': 0.05, 'RandomForestGini': 0.05}
	0.7703	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 8.89s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S26 (SBS44 - 0.97)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S27 (SBS88 - 0.92)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.80 GB / 15.43 GB (63.5%)
Disk Space Avail:   71.36 GB / 459.52 GB (15.5%)
===================================================
Train Data Rows:    14495
Train Data Columns: 123
Label Column:       S27 (SBS88 - 0.92)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10046.37 MB
	Train Data (Original)  Memory Usage: 11.98 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 26 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S27 (SBS88 - 0.92) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 26 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 26 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	122 features in original data used to generate 122 features in processed data.
	Train Data (Processed) Memory Usage: 10.98 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.75s of the 4.74s of remaining time.
	0.7248	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.64s of the 4.64s of remaining time.
	0.7255	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.54s of the 4.54s of remaining time.
	0.7945	 = Validation score   (accuracy)
	1.88s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.62s of the 2.62s of remaining time.
	0.7972	 = Validation score   (accuracy)
	2.48s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.12s of the 0.12s of remaining time.
	0.7676	 = Validation score   (accuracy)
	4.52s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.75s of the -4.59s of remaining time.
	Ensemble Weights: {'LightGBM': 0.75, 'KNeighborsUnif': 0.25}
	0.7979	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 9.68s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S27 (SBS88 - 0.92)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S28 (SBS92 - 0.95)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.76 GB / 15.43 GB (63.3%)
Disk Space Avail:   71.26 GB / 459.52 GB (15.5%)
===================================================
Train Data Rows:    14495
Train Data Columns: 124
Label Column:       S28 (SBS92 - 0.95)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    9997.47 MB
	Train Data (Original)  Memory Usage: 12.00 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 27 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S28 (SBS92 - 0.95) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 27 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 27 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	123 features in original data used to generate 123 features in processed data.
	Train Data (Processed) Memory Usage: 10.99 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.25s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.75s of the 4.75s of remaining time.
	0.7724	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.65s of the 4.64s of remaining time.
	0.7724	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.55s of the 4.55s of remaining time.
	0.8345	 = Validation score   (accuracy)
	2.05s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.45s of the 2.45s of remaining time.
	0.8276	 = Validation score   (accuracy)
	2.19s	 = Training   runtime
	0.01s	 = Validation runtime
Fitting model: RandomForestGini ... Training model for up to 0.24s of the 0.24s of remaining time.
	0.8131	 = Validation score   (accuracy)
	4.42s	 = Training   runtime
	0.07s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.75s of the -4.34s of remaining time.
	Ensemble Weights: {'LightGBMXT': 0.571, 'KNeighborsUnif': 0.143, 'LightGBM': 0.143, 'RandomForestGini': 0.143}
	0.84	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 9.44s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S28 (SBS92 - 0.95)")
No presets specified! To achieve strong results with AutoGluon, it is recommended to use the available presets.
	Recommended Presets (For more details refer to https://auto.gluon.ai/stable/tutorials/tabular/tabular-essentials.html#presets):
	presets='best_quality'   : Maximize accuracy. Default time_limit=3600.
	presets='high_quality'   : Strong accuracy with fast inference speed. Default time_limit=3600.
	presets='good_quality'   : Good accuracy with very fast inference speed. Default time_limit=3600.
	presets='medium_quality' : Fast training time, ideal for initial prototyping.
Beginning AutoGluon training ... Time limit = 5s
AutoGluon will save models to "AutogluonModels/ag-20240910_151915/Predictor_S29 (SBS97 - 0.95)"
=================== System Info ===================
AutoGluon Version:  1.1.0
Python Version:     3.10.12
Operating System:   Linux
Platform Machine:   x86_64
Platform Version:   #202405300957~1718348209~22.04~7817b67 SMP PREEMPT_DYNAMIC Mon J
CPU Count:          8
Memory Avail:       9.80 GB / 15.43 GB (63.5%)
Disk Space Avail:   71.17 GB / 459.52 GB (15.5%)
===================================================
Train Data Rows:    14495
Train Data Columns: 125
Label Column:       S29 (SBS97 - 0.95)
Problem Type:       binary
Preprocessing data ...
Selected class <--> label mapping:  class 1 = True, class 0 = False
Using Feature Generators to preprocess the data ...
Fitting AutoMLPipelineFeatureGenerator...
	Available Memory:                    10046.30 MB
	Train Data (Original)  Memory Usage: 12.01 MB (0.1% of available memory)
	Inferring data type of each feature based on column values. Set feature_metadata_in to manually specify special dtypes of the features.
	Stage 1 Generators:
		Fitting AsTypeFeatureGenerator...
			Note: Converting 28 features to boolean dtype as they only contain 2 unique values.
	Stage 2 Generators:
		Fitting FillNaFeatureGenerator...
	Stage 3 Generators:
		Fitting IdentityFeatureGenerator...
		Fitting CategoryFeatureGenerator...
			Fitting CategoryMemoryMinimizeFeatureGenerator...
	Stage 4 Generators:
		Fitting DropUniqueFeatureGenerator...

Fitting TabularPredictor for label: S29 (SBS97 - 0.95) ...

	Stage 5 Generators:
		Fitting DropDuplicatesFeatureGenerator...
	Unused Original Features (Count: 1): ['Unnamed: 0']
		These features were not used to generate any of the output features. Add a feature generator compatible with these features to utilize them.
		Features can also be unused if they carry very little information, such as being categorical but having almost entirely unique values or being duplicates of other features.
		These features do not need to be present at inference time.
		('object', []) : 1 | ['Unnamed: 0']
	Types of features in original data (raw dtype, special dtypes):
		('bool', []) : 28 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
		('int', [])  : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
	Types of features in processed data (raw dtype, special dtypes):
		('int', [])       : 96 | ['A[C>A]A', 'A[C>A]C', 'A[C>A]G', 'A[C>A]T', 'A[C>G]A', ...]
		('int', ['bool']) : 28 | ['S1 (SBS1 - 0.99)', 'S2 (SBS2 - 0.99)', 'S3 (SBS3 - 0.97)', 'S4 (SBS4 - 0.98)', 'S5 (SBS5 - 0.98)', ...]
	0.2s = Fit runtime
	124 features in original data used to generate 124 features in processed data.
	Train Data (Processed) Memory Usage: 11.00 MB (0.1% of available memory)
Data preprocessing and feature engineering runtime = 0.26s ...
AutoGluon will gauge predictive performance using evaluation metric: 'accuracy'
	To change this, specify the eval_metric parameter of Predictor()
Automatically generating train/validation split with holdout_frac=0.1, Train Rows: 13045, Val Rows: 1450
User-specified model hyperparameters to be fit:
{
	'NN_TORCH': {},
	'GBM': [{'extra_trees': True, 'ag_args': {'name_suffix': 'XT'}}, {}, 'GBMLarge'],
	'CAT': {},
	'XGB': {},
	'FASTAI': {},
	'RF': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'XT': [{'criterion': 'gini', 'ag_args': {'name_suffix': 'Gini', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'entropy', 'ag_args': {'name_suffix': 'Entr', 'problem_types': ['binary', 'multiclass']}}, {'criterion': 'squared_error', 'ag_args': {'name_suffix': 'MSE', 'problem_types': ['regression', 'quantile']}}],
	'KNN': [{'weights': 'uniform', 'ag_args': {'name_suffix': 'Unif'}}, {'weights': 'distance', 'ag_args': {'name_suffix': 'Dist'}}],
}
Fitting 13 L1 models ...
Fitting model: KNeighborsUnif ... Training model for up to 4.74s of the 4.74s of remaining time.
	0.7703	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: KNeighborsDist ... Training model for up to 4.64s of the 4.64s of remaining time.
	0.771	 = Validation score   (accuracy)
	0.03s	 = Training   runtime
	0.06s	 = Validation runtime
Fitting model: LightGBMXT ... Training model for up to 4.54s of the 4.54s of remaining time.
	0.8372	 = Validation score   (accuracy)
	2.17s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: LightGBM ... Training model for up to 2.32s of the 2.32s of remaining time.
	Ran out of time, early stopping on iteration 527. Best iteration is:
	[522]	valid_set's binary_error: 0.165517
	0.8345	 = Validation score   (accuracy)
	2.39s	 = Training   runtime
	0.02s	 = Validation runtime
Fitting model: WeightedEnsemble_L2 ... Training model for up to 4.74s of the -0.13s of remaining time.
	Ensemble Weights: {'LightGBMXT': 1.0}
	0.8372	 = Validation score   (accuracy)
	0.06s	 = Training   runtime
	0.0s	 = Validation runtime
AutoGluon training complete, total runtime = 5.23s ... Best model: "WeightedEnsemble_L2"
TabularPredictor saved. To load, use: predictor = TabularPredictor.load("AutogluonModels/ag-20240910_151915/Predictor_S29 (SBS97 - 0.95)")

MultilabelPredictor saved to disk. Load with: MultilabelPredictor.load('AutogluonModels/ag-20240910_151915')

In [10]:
evaluation = predictor.evaluate(test_df)

Evaluating TabularPredictor for label: S1 (SBS1 - 0.99) ...
Evaluating TabularPredictor for label: S2 (SBS2 - 0.99) ...
Evaluating TabularPredictor for label: S3 (SBS3 - 0.97) ...
Evaluating TabularPredictor for label: S4 (SBS4 - 0.98) ...
Evaluating TabularPredictor for label: S5 (SBS5 - 0.98) ...
Evaluating TabularPredictor for label: S6 (SBS7a - 1.00) ...
Evaluating TabularPredictor for label: S7 (SBS7b - 0.96) ...
Evaluating TabularPredictor for label: S8 (SBS8 - 0.92) ...
Evaluating TabularPredictor for label: S9 (SBS9 - 0.94) ...
Evaluating TabularPredictor for label: S10 (SBS10a - 1.00) ...
Evaluating TabularPredictor for label: S11 (SBS10d - 0.98) ...
Evaluating TabularPredictor for label: S12 (SBS11 - 0.99) ...
Evaluating TabularPredictor for label: S13 (SBS13 - 0.99) ...
Evaluating TabularPredictor for label: S14 (SBS14 - 0.98) ...
Evaluating TabularPredictor for label: S15 (SBS15 - 0.97) ...
Evaluating TabularPredictor for label: S16 (SBS17 - 0.99) ...
Evaluating TabularPredictor for label: S17 (SBS18 - 0.97) ...
Evaluating TabularPredictor for label: S18 (SBS19 - 0.95) ...
Evaluating TabularPredictor for label: S19 (SBS20 - 0.98) ...
Evaluating TabularPredictor for label: S20 (SBS22 - 0.99) ...
Evaluating TabularPredictor for label: S21 (SBS23 - 0.94) ...
Evaluating TabularPredictor for label: S22 (SBS26 - 0.94) ...
Evaluating TabularPredictor for label: S23 (SBS28 - 0.96) ...
Evaluating TabularPredictor for label: S24 (SBS31 - 0.98) ...
Evaluating TabularPredictor for label: S25 (SBS32 - 0.94) ...
Evaluating TabularPredictor for label: S26 (SBS44 - 0.97) ...
Evaluating TabularPredictor for label: S27 (SBS88 - 0.92) ...
Evaluating TabularPredictor for label: S28 (SBS92 - 0.95) ...
Evaluating TabularPredictor for label: S29 (SBS97 - 0.95) ...

In [11]:
x = test_df[0:1]
y = predictor.predict(x)

Predicting with TabularPredictor for label: S1 (SBS1 - 0.99) ...
Predicting with TabularPredictor for label: S2 (SBS2 - 0.99) ...
Predicting with TabularPredictor for label: S3 (SBS3 - 0.97) ...
Predicting with TabularPredictor for label: S4 (SBS4 - 0.98) ...
Predicting with TabularPredictor for label: S5 (SBS5 - 0.98) ...
Predicting with TabularPredictor for label: S6 (SBS7a - 1.00) ...
Predicting with TabularPredictor for label: S7 (SBS7b - 0.96) ...
Predicting with TabularPredictor for label: S8 (SBS8 - 0.92) ...
Predicting with TabularPredictor for label: S9 (SBS9 - 0.94) ...
Predicting with TabularPredictor for label: S10 (SBS10a - 1.00) ...
Predicting with TabularPredictor for label: S11 (SBS10d - 0.98) ...
Predicting with TabularPredictor for label: S12 (SBS11 - 0.99) ...
Predicting with TabularPredictor for label: S13 (SBS13 - 0.99) ...
Predicting with TabularPredictor for label: S14 (SBS14 - 0.98) ...
Predicting with TabularPredictor for label: S15 (SBS15 - 0.97) ...
Predicting with TabularPredictor for label: S16 (SBS17 - 0.99) ...
Predicting with TabularPredictor for label: S17 (SBS18 - 0.97) ...
Predicting with TabularPredictor for label: S18 (SBS19 - 0.95) ...
Predicting with TabularPredictor for label: S19 (SBS20 - 0.98) ...
Predicting with TabularPredictor for label: S20 (SBS22 - 0.99) ...
Predicting with TabularPredictor for label: S21 (SBS23 - 0.94) ...
Predicting with TabularPredictor for label: S22 (SBS26 - 0.94) ...
Predicting with TabularPredictor for label: S23 (SBS28 - 0.96) ...
Predicting with TabularPredictor for label: S24 (SBS31 - 0.98) ...
Predicting with TabularPredictor for label: S25 (SBS32 - 0.94) ...
Predicting with TabularPredictor for label: S26 (SBS44 - 0.97) ...
Predicting with TabularPredictor for label: S27 (SBS88 - 0.92) ...
Predicting with TabularPredictor for label: S28 (SBS92 - 0.95) ...
Predicting with TabularPredictor for label: S29 (SBS97 - 0.95) ...

In [27]:
evaluations = predictor.evaluate(test_df)

Evaluating TabularPredictor for label: S1 (SBS1 - 0.99) ...
Evaluating TabularPredictor for label: S2 (SBS2 - 0.99) ...
Evaluating TabularPredictor for label: S3 (SBS3 - 0.97) ...
Evaluating TabularPredictor for label: S4 (SBS4 - 0.98) ...
Evaluating TabularPredictor for label: S5 (SBS5 - 0.98) ...
Evaluating TabularPredictor for label: S6 (SBS7a - 1.00) ...
Evaluating TabularPredictor for label: S7 (SBS7b - 0.96) ...
Evaluating TabularPredictor for label: S8 (SBS8 - 0.92) ...
Evaluating TabularPredictor for label: S9 (SBS9 - 0.94) ...
Evaluating TabularPredictor for label: S10 (SBS10a - 1.00) ...
Evaluating TabularPredictor for label: S11 (SBS10d - 0.98) ...
Evaluating TabularPredictor for label: S12 (SBS11 - 0.99) ...
Evaluating TabularPredictor for label: S13 (SBS13 - 0.99) ...
Evaluating TabularPredictor for label: S14 (SBS14 - 0.98) ...
Evaluating TabularPredictor for label: S15 (SBS15 - 0.97) ...
Evaluating TabularPredictor for label: S16 (SBS17 - 0.99) ...
Evaluating TabularPredictor for label: S17 (SBS18 - 0.97) ...
Evaluating TabularPredictor for label: S18 (SBS19 - 0.95) ...
Evaluating TabularPredictor for label: S19 (SBS20 - 0.98) ...
Evaluating TabularPredictor for label: S20 (SBS22 - 0.99) ...
Evaluating TabularPredictor for label: S21 (SBS23 - 0.94) ...
Evaluating TabularPredictor for label: S22 (SBS26 - 0.94) ...
Evaluating TabularPredictor for label: S23 (SBS28 - 0.96) ...
Evaluating TabularPredictor for label: S24 (SBS31 - 0.98) ...
Evaluating TabularPredictor for label: S25 (SBS32 - 0.94) ...
Evaluating TabularPredictor for label: S26 (SBS44 - 0.97) ...
Evaluating TabularPredictor for label: S27 (SBS88 - 0.92) ...
Evaluating TabularPredictor for label: S28 (SBS92 - 0.95) ...
Evaluating TabularPredictor for label: S29 (SBS97 - 0.95) ...

In [28]:
for e in evaluations:
    print(evaluations[e])
    break

{'accuracy': 0.9776490066225165, 'balanced_accuracy': 0.7953065134099617, 'mcc': 0.675457418853395, 'roc_auc': 0.9852290868454661, 'f1': 0.9884203002144388, 'precision': 0.9834992887624466, 'recall': 0.9933908045977011}

In [24]:
for evaluation in evaluations:
    target_class = predictor.get_predictor(evaluation)
    best_model = target_class.leaderboard(silent=True).iloc[0]['model']
    evaluations[evaluation]['best_model'] = best_model

In [25]:
for e in evaluations:
    print(evaluations[e])
    break

{'accuracy': 0.9776490066225165, 'balanced_accuracy': 0.7953065134099617, 'mcc': 0.675457418853395, 'roc_auc': 0.9852290868454661, 'f1': 0.9884203002144388, 'precision': 0.9834992887624466, 'recall': 0.9933908045977011, 'best_model': 'LightGBMXT'}