In [47]:
import pandas as pd
import numpy as np
import sys
sys.path.append('../')
from utils.MultiLabelPredictor import MultilabelPredictor
from sklearn.metrics import mean_absolute_error, mean_squared_error

In [ ]:
multilabel_path = '../models/save/Predictior-1'
ml = MultilabelPredictor.load(multilabel_path)
test_df = pd.read_csv('../simulations/data/run_2/trinucleotides_counts_sampling_1.csv')
gt = pd.read_csv('../simulations/ground_truth/bin_exposures.csv')

evaluation_df = pd.merge(test_df, gt, on="Unnamed: 0")

In [49]:
prediction = ml.predict(test_df)

Predicting with TabularPredictor for label: S1 (SBS1 - 0.99) ...
Predicting with TabularPredictor for label: S2 (SBS2 - 0.99) ...
Predicting with TabularPredictor for label: S3 (SBS3 - 0.97) ...
Predicting with TabularPredictor for label: S4 (SBS4 - 0.98) ...
Predicting with TabularPredictor for label: S5 (SBS5 - 0.98) ...
Predicting with TabularPredictor for label: S6 (SBS7a - 1.00) ...
Predicting with TabularPredictor for label: S7 (SBS7b - 0.96) ...
Predicting with TabularPredictor for label: S8 (SBS8 - 0.92) ...
Predicting with TabularPredictor for label: S9 (SBS9 - 0.94) ...
Predicting with TabularPredictor for label: S10 (SBS10a - 1.00) ...
Predicting with TabularPredictor for label: S11 (SBS10d - 0.98) ...
Predicting with TabularPredictor for label: S12 (SBS11 - 0.99) ...
Predicting with TabularPredictor for label: S13 (SBS13 - 0.99) ...
Predicting with TabularPredictor for label: S14 (SBS14 - 0.98) ...
Predicting with TabularPredictor for label: S15 (SBS15 - 0.97) ...
Predicting with TabularPredictor for label: S16 (SBS17 - 0.99) ...
Predicting with TabularPredictor for label: S17 (SBS18 - 0.97) ...
Predicting with TabularPredictor for label: S18 (SBS19 - 0.95) ...
Predicting with TabularPredictor for label: S19 (SBS20 - 0.98) ...
Predicting with TabularPredictor for label: S20 (SBS22 - 0.99) ...
Predicting with TabularPredictor for label: S21 (SBS23 - 0.94) ...
Predicting with TabularPredictor for label: S22 (SBS26 - 0.94) ...
Predicting with TabularPredictor for label: S23 (SBS28 - 0.96) ...
Predicting with TabularPredictor for label: S24 (SBS31 - 0.98) ...
Predicting with TabularPredictor for label: S25 (SBS32 - 0.94) ...
Predicting with TabularPredictor for label: S26 (SBS44 - 0.97) ...
Predicting with TabularPredictor for label: S27 (SBS88 - 0.92) ...
Predicting with TabularPredictor for label: S28 (SBS92 - 0.95) ...
Predicting with TabularPredictor for label: S29 (SBS97 - 0.95) ...

In [ ]:
evaluations = ml.evaluate(evaluation_df.iloc[:,1:])

Evaluating TabularPredictor for label: S1 (SBS1 - 0.99) ...
Evaluating TabularPredictor for label: S2 (SBS2 - 0.99) ...
Evaluating TabularPredictor for label: S3 (SBS3 - 0.97) ...
Evaluating TabularPredictor for label: S4 (SBS4 - 0.98) ...
Evaluating TabularPredictor for label: S5 (SBS5 - 0.98) ...
Evaluating TabularPredictor for label: S6 (SBS7a - 1.00) ...
Evaluating TabularPredictor for label: S7 (SBS7b - 0.96) ...
Evaluating TabularPredictor for label: S8 (SBS8 - 0.92) ...
Evaluating TabularPredictor for label: S9 (SBS9 - 0.94) ...
Evaluating TabularPredictor for label: S10 (SBS10a - 1.00) ...
Evaluating TabularPredictor for label: S11 (SBS10d - 0.98) ...
Evaluating TabularPredictor for label: S12 (SBS11 - 0.99) ...
Evaluating TabularPredictor for label: S13 (SBS13 - 0.99) ...
Evaluating TabularPredictor for label: S14 (SBS14 - 0.98) ...
Evaluating TabularPredictor for label: S15 (SBS15 - 0.97) ...
Evaluating TabularPredictor for label: S16 (SBS17 - 0.99) ...
Evaluating TabularPredictor for label: S17 (SBS18 - 0.97) ...
Evaluating TabularPredictor for label: S18 (SBS19 - 0.95) ...
Evaluating TabularPredictor for label: S19 (SBS20 - 0.98) ...
Evaluating TabularPredictor for label: S20 (SBS22 - 0.99) ...
Evaluating TabularPredictor for label: S21 (SBS23 - 0.94) ...
Evaluating TabularPredictor for label: S22 (SBS26 - 0.94) ...
Evaluating TabularPredictor for label: S23 (SBS28 - 0.96) ...
Evaluating TabularPredictor for label: S24 (SBS31 - 0.98) ...
Evaluating TabularPredictor for label: S25 (SBS32 - 0.94) ...
Evaluating TabularPredictor for label: S26 (SBS44 - 0.97) ...
Evaluating TabularPredictor for label: S27 (SBS88 - 0.92) ...
Evaluating TabularPredictor for label: S28 (SBS92 - 0.95) ...
Evaluating TabularPredictor for label: S29 (SBS97 - 0.95) ...

In [39]:
pd.DataFrame(evaluations)

,S1 (SBS1 - 0.99),S2 (SBS2 - 0.99),S3 (SBS3 - 0.97),S4 (SBS4 - 0.98),S5 (SBS5 - 0.98),S6 (SBS7a - 1.00),S7 (SBS7b - 0.96),S8 (SBS8 - 0.92),S9 (SBS9 - 0.94),S10 (SBS10a - 1.00),...,S20 (SBS22 - 0.99),S21 (SBS23 - 0.94),S22 (SBS26 - 0.94),S23 (SBS28 - 0.96),S24 (SBS31 - 0.98),S25 (SBS32 - 0.94),S26 (SBS44 - 0.97),S27 (SBS88 - 0.92),S28 (SBS92 - 0.95),S29 (SBS97 - 0.95)
accuracy,0.989348,0.944533,0.905624,0.850764,0.936255,0.883437,0.855069,0.900160,0.888570,0.842155,...,0.806391,0.895027,0.906397,0.886914,0.937083,0.862244,0.823831,0.858877,0.852641,0.843093
balanced_accuracy,0.900598,0.873657,0.901347,0.849612,0.915787,0.796150,0.805455,0.895852,0.879733,0.814630,...,0.794896,0.751765,0.821986,0.795379,0.735607,0.818118,0.780290,0.831681,0.810142,0.745015
mcc,0.843199,0.773124,0.803395,0.698904,0.850338,0.647570,0.646428,0.796986,0.767744,0.655702,...,0.597388,0.586952,0.696353,0.658721,0.605071,0.660693,0.597369,0.682682,0.644015,0.542167
roc_auc,0.994870,0.978980,0.969640,0.933363,0.981570,0.928332,0.923898,0.964145,0.959122,0.915423,...,0.878894,0.918605,0.940887,0.909836,0.932643,0.925459,0.900775,0.929979,0.918689,0.864242
f1,0.994481,0.967682,0.921350,0.863531,0.954317,0.926920,0.740565,0.883253,0.858504,0.768758,...,0.756558,0.632677,0.747769,0.716950,0.610922,0.753360,0.714286,0.895011,0.896472,0.631210
precision,0.992580,0.961221,0.919743,0.865453,0.938322,0.899772,0.815492,0.907078,0.885884,0.840226,...,0.786126,0.773006,0.831624,0.837367,0.833333,0.802695,0.806061,0.871223,0.874168,0.731729
recall,0.996390,0.974229,0.922964,0.861617,0.970868,0.955759,0.678248,0.860646,0.832767,0.708495,...,0.729133,0.535469,0.679276,0.626812,0.482220,0.709737,0.641273,0.920135,0.919943,0.554973

In [56]:
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split
linear_gt = pd.read_csv('../simulations/ground_truth/bin_exposures.csv')
exposure = pd.read_csv('../simulations/ground_truth/exposures.csv')

X_train, X_test, y_train, y_test = train_test_split(linear_gt.iloc[:,1:], exposure.iloc[:,1:], train_size=0.2, random_state=42)

In [57]:
X_train

,S1 (SBS1 - 0.99),S2 (SBS2 - 0.99),S3 (SBS3 - 0.97),S4 (SBS4 - 0.98),S5 (SBS5 - 0.98),S6 (SBS7a - 1.00),S7 (SBS7b - 0.96),S8 (SBS8 - 0.92),S9 (SBS9 - 0.94),S10 (SBS10a - 1.00),...,S20 (SBS22 - 0.99),S21 (SBS23 - 0.94),S22 (SBS26 - 0.94),S23 (SBS28 - 0.96),S24 (SBS31 - 0.98),S25 (SBS32 - 0.94),S26 (SBS44 - 0.97),S27 (SBS88 - 0.92),S28 (SBS92 - 0.95),S29 (SBS97 - 0.95)
8547,True,True,False,False,True,True,False,False,False,False,...,False,False,False,False,False,False,False,True,True,False
5184,True,True,True,True,True,True,False,True,False,False,...,False,False,False,True,False,False,False,True,True,False
1461,True,True,True,True,True,True,False,True,False,False,...,False,False,False,False,False,True,False,True,True,False
15893,True,True,True,True,True,True,False,False,False,False,...,False,False,False,False,False,False,True,True,True,False
17596,True,True,True,True,True,True,False,True,False,False,...,True,False,False,True,True,False,False,True,True,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,True,True,False,True,True,False,True,False,True,True,...,False,True,True,False,True,False,True,True,True,False
11964,True,True,True,False,True,True,False,True,True,False,...,True,False,True,False,False,False,False,True,True,False
5390,True,False,False,False,True,True,False,True,True,False,...,False,False,False,False,False,True,False,True,False,False
860,True,True,False,True,True,True,True,True,False,False,...,True,False,True,False,False,False,True,True,True,True
15795,True,True,True,False,True,False,False,True,False,False,...,False,False,True,False,True,False,False,False,True,False

In [58]:
y_train

,S1 (SBS1 - 0.99),S2 (SBS2 - 0.99),S3 (SBS3 - 0.97),S4 (SBS4 - 0.98),S5 (SBS5 - 0.98),S6 (SBS7a - 1.00),S7 (SBS7b - 0.96),S8 (SBS8 - 0.92),S9 (SBS9 - 0.94),S10 (SBS10a - 1.00),...,S20 (SBS22 - 0.99),S21 (SBS23 - 0.94),S22 (SBS26 - 0.94),S23 (SBS28 - 0.96),S24 (SBS31 - 0.98),S25 (SBS32 - 0.94),S26 (SBS44 - 0.97),S27 (SBS88 - 0.92),S28 (SBS92 - 0.95),S29 (SBS97 - 0.95)
8547,1155.176332,564.302477,0.000000,0.000000,566.891410,82.780859,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,136.201878,237.719646,0.000000
5184,2898.989980,560.159927,3319.841207,7804.781945,2045.647663,149.323955,0.000000,3856.295014,0.000000,0.000000,...,0.000000,0.000000,0.000000,9.831865,0.000000,0.000000,0.000000,381.140877,6815.565635,0.000000
1461,2396.936697,191.060485,5938.031509,448.527147,883.745585,204.066683,0.000000,2173.337051,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,239.102047,0.000000,64.899339,141.011453,0.000000
15893,364.737936,34.734373,147.024108,1.445221,657.782384,14.519637,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,8.787460,33.341072,91.989745,0.000000
17596,994.977879,125.101327,3938.569320,628.783927,500.278650,88.767751,0.000000,2919.409691,0.000000,0.000000,...,20.593087,0.000000,0.000000,44.452745,30.905511,0.000000,0.000000,188.714767,961.482883,95.999446
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
11284,2017.705043,2393.846759,0.000000,566.488736,2025.746584,0.000000,425.639824,0.000000,315.572115,18.788455,...,0.000000,177.568192,52.025055,0.000000,72.471221,0.000000,82.751171,22.116111,2243.476472,0.000000
11964,1419.279896,149.312229,633.320295,0.000000,466.420565,65.570081,0.000000,571.701742,1117.967854,0.000000,...,33.736621,0.000000,183.994260,0.000000,0.000000,0.000000,0.000000,436.055103,565.161338,0.000000
5390,440.318645,0.000000,0.000000,0.000000,564.173874,6.622867,0.000000,187.780397,287.849966,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,19.274556,0.000000,47.074926,0.000000,0.000000
860,397.616273,267.325511,0.000000,2085.898740,3724.473660,85.919959,143.562565,1325.257663,0.000000,0.000000,...,458.147192,0.000000,590.497802,0.000000,0.000000,0.000000,61.528791,319.157543,1455.571282,162.078466
15795,1117.771972,58.491506,3233.449366,0.000000,1327.688947,0.000000,0.000000,1095.584320,0.000000,0.000000,...,0.000000,0.000000,29.790842,0.000000,32.495074,0.000000,0.000000,0.000000,175.038638,0.000000

In [59]:
reg = LinearRegression()

reg.fit(X_train, y_train)
prediction = reg.predict(X_test)

print(mean_absolute_error(prediction, y_test))
print(mean_squared_error(prediction, y_test))

1794.816297869605
216077700.58874747